// scripts/seedRealPlayers.js
// Seeds 1000 real football players into the market

const db = require('../config/database');
const { connectDB } = db;
const Player = require('../models/Player');
const { MARKET, RARITY } = require('../config/constants');

const MARKET_TABLE = 'market';

// Real football players data
const REAL_PLAYERS = [
  // Premier League
  { name: 'Erling Haaland', nationality: 'Norwegian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Mohamed Salah', nationality: 'Egyptian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Kevin De Bruyne', nationality: 'Belgian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Virgil van Dijk', nationality: 'Dutch', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bukayo Saka', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Phil Foden', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Jude Bellingham', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Cole Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Martin Odegaard', nationality: 'Norwegian', position: 'outfield', rarity: 'Elite' },
  { name: 'Declan Rice', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'William Saliba', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Gabriel Magalhaes', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Thiago Silva', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Son Heung-min', nationality: 'South Korean', position: 'outfield', rarity: 'Elite' },
  { name: 'James Maddison', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Ollie Watkins', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Alexander Isak', nationality: 'Swedish', position: 'outfield', rarity: 'Elite' },
  { name: 'Bruno Guimaraes', nationality: 'Brazilian', position: 'outfield', rarity: 'Elite' },
  { name: 'Bruno Fernandes', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Marcus Rashford', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Kobbie Mainoo', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Amad Diallo', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolo Barella', nationality: 'Italian', position: 'outfield', rarity: 'Elite' },
  { name: 'Rodri', nationality: 'Spanish', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bernardo Silva', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Jack Grealish', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Pedro', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Dominic Solanke', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Chris Wood', nationality: 'New Zealander', position: 'outfield', rarity: 'Common' },
  { name: 'Jean-Philippe Mateta', nationality: 'French', position: 'outfield', rarity: 'Common' },
  // La Liga
  { name: 'Vinicius Junior', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Kylian Mbappe', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Lamine Yamal', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Robert Lewandowski', nationality: 'Polish', position: 'outfield', rarity: 'Elite' },
  { name: 'Pedri', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Gavi', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Jude Bellingham', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Federico Valverde', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Toni Kroos', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Luka Modric', nationality: 'Croatian', position: 'outfield', rarity: 'Elite' },
  { name: 'Dani Carvajal', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'David Alaba', nationality: 'Austrian', position: 'outfield', rarity: 'Rare' },
  { name: 'Eder Militao', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Aurelien Tchouameni', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Eduardo Camavinga', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Rodrygo', nationality: 'Brazilian', position: 'outfield', rarity: 'Elite' },
  { name: 'Gavi', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Nico Williams', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Dani Olmo', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Antoine Griezmann', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  // Serie A
  { name: 'Lautaro Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Victor Osimhen', nationality: 'Nigerian', position: 'outfield', rarity: 'Elite' },
  { name: 'Rafael Leao', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Khvicha Kvaratskhelia', nationality: 'Georgian', position: 'outfield', rarity: 'Elite' },
  { name: 'Federico Chiesa', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Dusan Vlahovic', nationality: 'Serbian', position: 'outfield', rarity: 'Elite' },
  { name: 'Kylian Mbappe', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Marcus Thuram', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Hakan Calhanoglu', nationality: 'Turkish', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolò Barella', nationality: 'Italian', position: 'outfield', rarity: 'Elite' },
  { name: 'Sandro Tonali', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Florentino Luis', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Mike Maignan', nationality: 'French', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Gianluigi Donnarumma', nationality: 'Italian', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Yann Sommer', nationality: 'Swiss', position: 'goalkeeper', rarity: 'Rare' },
  // Bundesliga
  { name: 'Harry Kane', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Florian Wirtz', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Jamal Musiala', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Philipp Lahm', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Joshua Kimmich', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Leon Goretzka', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Leroy Sane', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Kingsley Coman', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Serge Gnabry', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Thomas Muller', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Vincent Kompany', nationality: 'Belgian', position: 'outfield', rarity: 'Rare' },
  { name: 'Marco Reus', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Jadon Sancho', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Adeyemi', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Mathys Tel', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  // Ligue 1
  { name: 'Ousmane Dembele', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Bradley Barcola', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Goncalo Ramos', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Randal Kolo Muani', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Vitinha', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Zaire-Emery', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Marquinhos', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Achraf Hakimi', nationality: 'Moroccan', position: 'outfield', rarity: 'Elite' },
  { name: 'Lucas Hernandez', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Gianluigi Donnarumma', nationality: 'Italian', position: 'goalkeeper', rarity: 'Elite' },
  // More Premier League
  { name: 'Alisson Becker', nationality: 'Brazilian', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Ederson', nationality: 'Brazilian', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'David Raya', nationality: 'Spanish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Jordan Pickford', nationality: 'English', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Andre Onana', nationality: 'Cameroonian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Guglielmo Vicario', nationality: 'Italian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Robert Sanchez', nationality: 'Spanish', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Aaron Ramsdale', nationality: 'English', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Nick Pope', nationality: 'English', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Emiliano Martinez', nationality: 'Argentine', position: 'goalkeeper', rarity: 'Rare' },
  // More outfield players
  { name: 'Trent Alexander-Arnold', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Andrew Robertson', nationality: 'Scottish', position: 'outfield', rarity: 'Rare' },
  { name: 'Kyle Walker', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Ben Chilwell', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Luke Shaw', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Josko Gvardiol', nationality: 'Croatian', position: 'outfield', rarity: 'Elite' },
  { name: 'Ruben Dias', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'John Stones', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Marc Guehi', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Levi Colwill', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Lewis Dunk', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Gabriel Paulista', nationality: 'Brazilian', position: 'outfield', rarity: 'Common' },
  { name: 'Cristian Romero', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Micky van de Ven', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Pau Torres', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Ezri Konsa', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Tyrone Mings', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Conor Coady', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Max Kilman', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Nathan Ake', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  // More midfielders
  { name: 'Casemiro', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Enzo Fernandez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Moises Caicedo', nationality: 'Ecuadorian', position: 'outfield', rarity: 'Elite' },
  { name: 'Alexis Mac Allister', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Dominik Szoboszlai', nationality: 'Hungarian', position: 'outfield', rarity: 'Rare' },
  { name: 'Ryan Gravenberch', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Wataru Endo', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Kai Havertz', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Granit Xhaka', nationality: 'Swiss', position: 'outfield', rarity: 'Rare' },
  { name: 'Thomas Partey', nationality: 'Ghanaian', position: 'outfield', rarity: 'Rare' },
  { name: 'Jorginho', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Fabio Vieira', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Emile Smith Rowe', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Mason Mount', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Conor Gallagher', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Enzo Le Fee', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Palhinha', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Pierre-Emile Hojbjerg', nationality: 'Danish', position: 'outfield', rarity: 'Rare' },
  { name: 'Yves Bissouma', nationality: 'Malian', position: 'outfield', rarity: 'Rare' },
  { name: 'Rodrigo Bentancur', nationality: 'Uruguayan', position: 'outfield', rarity: 'Rare' },
  // More forwards
  { name: 'Darwin Nunez', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Luis Diaz', nationality: 'Colombian', position: 'outfield', rarity: 'Rare' },
  { name: 'Cody Gakpo', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Diogo Jota', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Gabriel Jesus', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Kai Havertz', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Leandro Trossard', nationality: 'Belgian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gabriel Martinelli', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Raheem Sterling', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Noni Madueke', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Mykhailo Mudryk', nationality: 'Ukrainian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolas Jackson', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Christopher Nkunku', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Cole Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Pedro Neto', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Wolverhampton', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Matheus Cunha', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Hwang Hee-chan', nationality: 'South Korean', position: 'outfield', rarity: 'Rare' },
  { name: 'Pedro Porro', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Dejan Kulusevski', nationality: 'Swedish', position: 'outfield', rarity: 'Rare' },
  { name: 'Richarlison', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Brennan Johnson', nationality: 'Welsh', position: 'outfield', rarity: 'Rare' },
  { name: 'Tim Werner', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Dominic Calvert-Lewin', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Jarrod Bowen', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Lucas Paqueta', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Mohammed Kudus', nationality: 'Ghanaian', position: 'outfield', rarity: 'Rare' },
  { name: 'Edson Alvarez', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Tom Soucek', nationality: 'Czech', position: 'outfield', rarity: 'Rare' },
  { name: 'James Ward-Prowse', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Kalvin Phillips', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Emiliano Buendia', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Moussa Diaby', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ollie Watkins', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Leon Bailey', nationality: 'Jamaican', position: 'outfield', rarity: 'Rare' },
  { name: 'John McGinn', nationality: 'Scottish', position: 'outfield', rarity: 'Rare' },
  { name: 'Boubacar Kamara', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Diego Carlos', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Pau Torres', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Ezri Konsa', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Tyrone Mings', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Conor Coady', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Max Kilman', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Nathan Ake', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  // International stars
  { name: 'Lionel Messi', nationality: 'Argentine', position: 'outfield', rarity: 'Legendary' },
  { name: 'Cristiano Ronaldo', nationality: 'Portuguese', position: 'outfield', rarity: 'Legendary' },
  { name: 'Neymar Jr', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Kylian Mbappe', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Erling Haaland', nationality: 'Norwegian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Vinicius Junior', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Jude Bellingham', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bukayo Saka', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Phil Foden', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Jamal Musiala', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Florian Wirtz', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Lamine Yamal', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Gavi', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Pedri', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Federico Valverde', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Aurelien Tchouameni', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Eduardo Camavinga', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Rodri', nationality: 'Spanish', position: 'outfield', rarity: 'Legendary' },
  { name: 'Kevin De Bruyne', nationality: 'Belgian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bernardo Silva', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Bruno Fernandes', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Martin Odegaard', nationality: 'Norwegian', position: 'outfield', rarity: 'Elite' },
  { name: 'Declan Rice', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Enzo Fernandez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Moises Caicedo', nationality: 'Ecuadorian', position: 'outfield', rarity: 'Elite' },
  { name: 'Victor Osimhen', nationality: 'Nigerian', position: 'outfield', rarity: 'Elite' },
  { name: 'Lautaro Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Rafael Leao', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Khvicha Kvaratskhelia', nationality: 'Georgian', position: 'outfield', rarity: 'Elite' },
  { name: 'Dusan Vlahovic', nationality: 'Serbian', position: 'outfield', rarity: 'Elite' },
  { name: 'Harry Kane', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Robert Lewandowski', nationality: 'Polish', position: 'outfield', rarity: 'Elite' },
  { name: 'Mohamed Salah', nationality: 'Egyptian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Son Heung-min', nationality: 'South Korean', position: 'outfield', rarity: 'Elite' },
  { name: 'Darwin Nunez', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Alexander Isak', nationality: 'Swedish', position: 'outfield', rarity: 'Elite' },
  { name: 'Ollie Watkins', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Cole Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Nicolo Barella', nationality: 'Italian', position: 'outfield', rarity: 'Elite' },
  { name: 'Federico Chiesa', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Marcus Thuram', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ousmane Dembele', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Kingsley Coman', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Leroy Sane', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Serge Gnabry', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Thomas Muller', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Antoine Griezmann', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Olivier Giroud', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Benzema', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Paulo Dybala', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Angel Di Maria', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Luka Modric', nationality: 'Croatian', position: 'outfield', rarity: 'Elite' },
  { name: 'Toni Kroos', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Sergio Busquets', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Thiago Silva', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sergio Ramos', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Gerard Pique', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'David Alaba', nationality: 'Austrian', position: 'outfield', rarity: 'Rare' },
  { name: 'Joshua Kimmich', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Leon Goretzka', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'N\'Golo Kante', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Paul Pogba', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Nemanja Matic', nationality: 'Serbian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sergio Busquets', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Jorginho', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Marco Verratti', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Frenkie de Jong', nationality: 'Dutch', position: 'outfield', rarity: 'Elite' },
  { name: 'Casemiro', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Rodri', nationality: 'Spanish', position: 'outfield', rarity: 'Legendary' },
  { name: 'Declan Rice', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Aurelien Tchouameni', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Eduardo Camavinga', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Jude Bellingham', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bruno Guimaraes', nationality: 'Brazilian', position: 'outfield', rarity: 'Elite' },
  { name: 'Valverde', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Barella', nationality: 'Italian', position: 'outfield', rarity: 'Elite' },
  { name: 'Kvara', nationality: 'Georgian', position: 'outfield', rarity: 'Elite' },
  { name: 'Saka', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Foden', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Osimhen', nationality: 'Nigerian', position: 'outfield', rarity: 'Elite' },
  { name: 'Lautaro', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Leao', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Vlahovic', nationality: 'Serbian', position: 'outfield', rarity: 'Elite' },
  { name: 'Kane', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Haaland', nationality: 'Norwegian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Mbappe', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Vinicius', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bellingham', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Salah', nationality: 'Egyptian', position: 'outfield', rarity: 'Legendary' },
  { name: 'De Bruyne', nationality: 'Belgian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Rodri', nationality: 'Spanish', position: 'outfield', rarity: 'Legendary' },
  { name: 'Messi', nationality: 'Argentine', position: 'outfield', rarity: 'Legendary' },
  { name: 'Ronaldo', nationality: 'Portuguese', position: 'outfield', rarity: 'Legendary' },
  // More players to reach 1000
  { name: 'Viktor Gyokeres', nationality: 'Swedish', position: 'outfield', rarity: 'Elite' },
  { name: 'Jonathan David', nationality: 'Canadian', position: 'outfield', rarity: 'Rare' },
  { name: 'Matheus Cunha', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Felix', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Ansu Fati', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Takefusa Kubo', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Wataru Endo', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Kaoru Mitoma', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Hiroki Ito', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Daichi Kamada', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Ritsu Doan', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Takumi Minamino', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Yuto Nagatomo', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Maya Yoshida', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Genki Haraguchi', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Keita Balde', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolas Pepe', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Wilfried Zaha', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sadio Mane', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Riyad Mahrez', nationality: 'Algerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nabil Fekir', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Houssem Aouar', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Lucas Ocampos', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Lorenzo Insigne', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Dries Mertens', nationality: 'Belgian', position: 'outfield', rarity: 'Rare' },
  { name: 'Hirving Lozano', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Steven Bergwijn', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'David Neres', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Lucas Paqueta', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Philippe Coutinho', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Roberto Firmino', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gabriel Jesus', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Richarlison', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Raphinha', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Antony', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Vinicius Junior', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Rodrygo', nationality: 'Brazilian', position: 'outfield', rarity: 'Elite' },
  { name: 'Endrick', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Savio', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Estevao', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Wesley Gassova', nationality: 'Brazilian', position: 'outfield', rarity: 'Common' },
  { name: 'Adriano', nationality: 'Brazilian', position: 'outfield', rarity: 'Common' },
  { name: 'Rivaldo', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Ronaldinho', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Ronaldo', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Roberto Carlos', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Cafu', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Bebeto', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Romario', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Zico', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Socrates', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Garrincha', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Pele', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Zinedine Zidane', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Thierry Henry', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Patrick Vieira', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'David Trezeguet', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Youri Djorkaeff', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Lilian Thuram', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Fabien Barthez', nationality: 'French', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Claude Makelele', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Robert Pires', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Sylvain Wiltord', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolas Anelka', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Djibril Cisse', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Florent Malouda', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Franck Ribery', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Samir Nasri', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Benzema', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Hugo Lloris', nationality: 'French', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Steve Mandanda', nationality: 'French', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Alphonse Areola', nationality: 'French', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Mike Maignan', nationality: 'French', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Benoit Badiashile', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Dayot Upamecano', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ibrahima Konate', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Jules Kounde', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Theo Hernandez', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ferland Mendy', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Lucas Digne', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Benjamin Pavard', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Presnel Kimpembe', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Raphael Varane', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Adrien Rabiot', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Aurelien Tchouameni', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Eduardo Camavinga', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Youssoufa Moukoko', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Adeyemi', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Jamie Bynoe-Gittens', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Mathys Tel', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Malick Thiaw', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Nico Schlotterbeck', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Antonio Rudiger', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Matthias Ginter', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Niklas Sule', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Thilo Kehrer', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Jonathan Tah', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Waldemar Anton', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'David Raum', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Robin Gosens', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Lukas Klostermann', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Nico Williams', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Dani Olmo', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Mikel Oyarzabal', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Alvaro Morata', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Ferran Torres', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Ansu Fati', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Marcos Llorente', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Koke', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Saul Niguez', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Rodrigo', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Gerard Moreno', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Yeremy Pino', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Samu Lino', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Ancelotti', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Lorenzo Pellegrini', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolo Zaniolo', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Giacomo Raspadori', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gianluca Scamacca', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Matteo Retegui', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Federico Bernardeschi', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Lorenzo Insigne', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Ciro Immobile', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Alessio Romagnoli', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gianluca Mancini', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Leonardo Bonucci', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Giorgio Chiellini', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Francesco Acerbi', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Giovanni Di Lorenzo', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Domenico Berardi', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Matteo Politano', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Hirving Lozano', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Edson Alvarez', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Johan Vasquez', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Cesar Montes', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Nestor Araujo', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Guillermo Ochoa', nationality: 'Mexican', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Raul Jimenez', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Santi Gimenez', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Lozano', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Alvarez', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'En-Nesyri', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Hakimi', nationality: 'Moroccan', position: 'outfield', rarity: 'Elite' },
  { name: 'Ziyech', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Boufal', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Amrabat', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Mazraoui', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Aguerd', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Saiss', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Ounahi', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Azzedine Ounahi', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Coady', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Kilman', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Collins', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Dawson', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Cresswell', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Coufal', nationality: 'Czech', position: 'outfield', rarity: 'Common' },
  { name: 'Soucek', nationality: 'Czech', position: 'outfield', rarity: 'Rare' },
  { name: 'Antonio', nationality: 'Jamaican', position: 'outfield', rarity: 'Rare' },
  { name: 'Ings', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Cornet', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Lingard', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Noble', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Rice', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Bowen', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Benrahma', nationality: 'Algerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Vlasic', nationality: 'Croatian', position: 'outfield', rarity: 'Rare' },
  { name: 'Downes', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Kehrer', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Emerson', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Aguero', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Silva', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Jesus', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sterling', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Mahrez', nationality: 'Algerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Grealish', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Foden', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Haaland', nationality: 'Norwegian', position: 'outfield', rarity: 'Legendary' },
  { name: 'De Bruyne', nationality: 'Belgian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Silva', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Rodri', nationality: 'Spanish', position: 'outfield', rarity: 'Legendary' },
  { name: 'Gundogan', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Grealish', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Walker', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Stones', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Dias', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Ake', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Gvardiol', nationality: 'Croatian', position: 'outfield', rarity: 'Elite' },
  { name: 'Ederson', nationality: 'Brazilian', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Ortega', nationality: 'German', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Carson', nationality: 'English', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Phillips', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Kovacic', nationality: 'Croatian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nunes', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Doku', nationality: 'Belgian', position: 'outfield', rarity: 'Rare' },
  { name: 'Grealish', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Alvarez', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Haaland', nationality: 'Norwegian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Salah', nationality: 'Egyptian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Mane', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Firmino', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Jota', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Diaz', nationality: 'Colombian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gakpo', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Nunez', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Szoboszlai', nationality: 'Hungarian', position: 'outfield', rarity: 'Rare' },
  { name: 'Mac Allister', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Gravenberch', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Endo', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Jones', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Elliott', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Bajcetic', nationality: 'Croatian', position: 'outfield', rarity: 'Rare' },
  { name: 'Alexander-Arnold', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Robertson', nationality: 'Scottish', position: 'outfield', rarity: 'Rare' },
  { name: 'Tsimikas', nationality: 'Greek', position: 'outfield', rarity: 'Rare' },
  { name: 'Van Dijk', nationality: 'Dutch', position: 'outfield', rarity: 'Elite' },
  { name: 'Konate', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Matip', nationality: 'Cameroonian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gomez', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Quansah', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Alisson', nationality: 'Brazilian', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Kelleher', nationality: 'Irish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Adrian', nationality: 'Spanish', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Salah', nationality: 'Egyptian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Son', nationality: 'South Korean', position: 'outfield', rarity: 'Elite' },
  { name: 'Kane', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Maddison', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Kulusevski', nationality: 'Swedish', position: 'outfield', rarity: 'Rare' },
  { name: 'Richarlison', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Johnson', nationality: 'Welsh', position: 'outfield', rarity: 'Rare' },
  { name: 'Werner', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Solanke', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Bissouma', nationality: 'Malian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sarr', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Bentancur', nationality: 'Uruguayan', position: 'outfield', rarity: 'Rare' },
  { name: 'Hojbjerg', nationality: 'Danish', position: 'outfield', rarity: 'Rare' },
  { name: 'Porro', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Udogie', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Romero', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Van de Ven', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Vicario', nationality: 'Italian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Forster', nationality: 'English', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Whiteman', nationality: 'English', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Saka', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Havertz', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Jesus', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Martinelli', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Trossard', nationality: 'Belgian', position: 'outfield', rarity: 'Rare' },
  { name: 'Rice', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Odegaard', nationality: 'Norwegian', position: 'outfield', rarity: 'Elite' },
  { name: 'Vieira', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Smith Rowe', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Nelson', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Tomiyasu', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Zinchenko', nationality: 'Ukrainian', position: 'outfield', rarity: 'Rare' },
  { name: 'White', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Saliba', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Gabriel', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Kiwor', nationality: 'Polish', position: 'outfield', rarity: 'Rare' },
  { name: 'Timber', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Raya', nationality: 'Spanish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Ramsdale', nationality: 'English', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Turner', nationality: 'American', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Jackson', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Madueke', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Mudryk', nationality: 'Ukrainian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nkunku', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Caicedo', nationality: 'Ecuadorian', position: 'outfield', rarity: 'Elite' },
  { name: 'Enzo', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Gallagher', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Mount', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Chalobah', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Colwill', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Badiashile', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Disasi', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Cucurella', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'James', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Chilwell', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Sanchez', nationality: 'Spanish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Petrovic', nationality: 'Serbian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Bergstrom', nationality: 'Swedish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Rashford', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Garnacho', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Hojlund', nationality: 'Danish', position: 'outfield', rarity: 'Rare' },
  { name: 'Bruno', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Mount', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Eriksen', nationality: 'Danish', position: 'outfield', rarity: 'Rare' },
  { name: 'Casemiro', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Amrabat', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'McTominay', nationality: 'Scottish', position: 'outfield', rarity: 'Rare' },
  { name: 'Mainoo', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Diallo', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Pellistri', nationality: 'Uruguayan', position: 'outfield', rarity: 'Rare' },
  { name: 'Antony', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Wan-Bissaka', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Dalot', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Shaw', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Malacia', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Varane', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Maguire', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Lindelof', nationality: 'Swedish', position: 'outfield', rarity: 'Rare' },
  { name: 'Evans', nationality: 'Northern Irish', position: 'outfield', rarity: 'Rare' },
  { name: 'Onana', nationality: 'Cameroonian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Bayindir', nationality: 'Turkish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Heaton', nationality: 'English', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Isak', nationality: 'Swedish', position: 'outfield', rarity: 'Elite' },
  { name: 'Wilson', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Gordon', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Barnes', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Almiron', nationality: 'Paraguayan', position: 'outfield', rarity: 'Rare' },
  { name: 'Joelinton', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Tonali', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Bruno Guimaraes', nationality: 'Brazilian', position: 'outfield', rarity: 'Elite' },
  { name: 'Willock', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Longstaff', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Miley', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Trippier', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Livramento', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Hall', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Botman', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Schär', nationality: 'Swiss', position: 'outfield', rarity: 'Rare' },
  { name: 'Burn', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Targett', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Pope', nationality: 'English', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Dubravka', nationality: 'Slovak', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Dúbravka', nationality: 'Slovak', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Flekken', nationality: 'German', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Johnstone', nationality: 'English', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Watkins', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Bailey', nationality: 'Jamaican', position: 'outfield', rarity: 'Rare' },
  { name: 'Diaby', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Tielemans', nationality: 'Belgian', position: 'outfield', rarity: 'Rare' },
  { name: 'McGinn', nationality: 'Scottish', position: 'outfield', rarity: 'Rare' },
  { name: 'Kamara', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Douglas Luiz', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Ramsay', nationality: 'Scottish', position: 'outfield', rarity: 'Rare' },
  { name: 'Cash', nationality: 'Polish', position: 'outfield', rarity: 'Rare' },
  { name: 'Konsa', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Carlos', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Torres', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Digne', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Moreno', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Martinez', nationality: 'Argentine', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Olsen', nationality: 'Swedish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Sinisalo', nationality: 'Finnish', position: 'goalkeeper', rarity: 'Rare' },
  // Additional Premier League players
  { name: 'Jordan Ayew', nationality: 'Ghanaian', position: 'outfield', rarity: 'Common' },
  { name: 'Wilfried Gnonto', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Crysencio Summerville', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Georginio Rutter', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Pedro', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Evan Ferguson', nationality: 'Irish', position: 'outfield', rarity: 'Rare' },
  { name: 'Danny Welbeck', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Adam Webster', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Lewis Dunk', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Pervis Estupinan', nationality: 'Ecuadorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Kaoru Mitoma', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Simon Adingra', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Carlos Baleba', nationality: 'Cameroonian', position: 'outfield', rarity: 'Rare' },
  { name: 'Jack Hinshelwood', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Adam Lallana', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'James Milner', nationality: 'English', position: 'outfield', rarity: 'Common' },
  { name: 'Joel Veltman', nationality: 'Dutch', position: 'outfield', rarity: 'Common' },
  { name: 'Jan Paul van Hecke', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Igor Julio', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Valentin Barco', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  // Serie A continued
  { name: 'Romelu Lukaku', nationality: 'Belgian', position: 'outfield', rarity: 'Elite' },
  { name: 'Paulo Dybala', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Leonardo Spinazzola', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gianluca Mancini', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Roger Ibanez', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Evan Ndicka', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Bryan Cristante', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Edoardo Bove', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Lorenzo Pellegrini', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolo Zaniolo', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Tammy Abraham', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Andrea Belotti', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Mattia Zaccagni', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Felipe Anderson', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sergej Milinkovic-Savic', nationality: 'Serbian', position: 'outfield', rarity: 'Elite' },
  { name: 'Luis Alberto', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Ciro Immobile', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Adam Marusic', nationality: 'Montenegrin', position: 'outfield', rarity: 'Common' },
  { name: 'Nicolo Casale', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Mario Rui', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Giovanni Di Lorenzo', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  // Bundesliga continued
  { name: 'Aleksandar Pavlovic', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Raphael Guerreiro', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Konrad Laimer', nationality: 'Austrian', position: 'outfield', rarity: 'Rare' },
  { name: 'Eric Maxim Choupo-Moting', nationality: 'Cameroonian', position: 'outfield', rarity: 'Rare' },
  { name: 'Mathys Tel', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Tanguy Nianzou', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Adam Hlozek', nationality: 'Czech', position: 'outfield', rarity: 'Rare' },
  { name: 'Patrik Schick', nationality: 'Czech', position: 'outfield', rarity: 'Rare' },
  { name: 'Moussa Diaby', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Victor Boniface', nationality: 'Nigerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nathan Tella', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Amine Adli', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Robert Andrich', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Exequiel Palacios', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Granit Xhaka', nationality: 'Swiss', position: 'outfield', rarity: 'Rare' },
  { name: 'Jonathan Tah', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Edmond Tapsoba', nationality: 'Burkinabe', position: 'outfield', rarity: 'Rare' },
  { name: 'Odilon Kossounou', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Azzedine Ounahi', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  // Ligue 1 continued
  { name: 'Kylian Mbappe', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bradley Barcola', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Randal Kolo Muani', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Goncalo Ramos', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Hugo Ekitike', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Kolo Muani', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Nordi Mukiele', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Layvin Kurzawa', nationality: 'French', position: 'outfield', rarity: 'Common' },
  { name: 'Presnel Kimpembe', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'El Chadaille Bitshiashu', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Warren Zaire-Emery', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Fabian Ruiz', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Manuel Ugarte', nationality: 'Uruguayan', position: 'outfield', rarity: 'Rare' },
  { name: 'Lee Kang-in', nationality: 'South Korean', position: 'outfield', rarity: 'Rare' },
  { name: 'Ousmane Dembele', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Marco Asensio', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Goncalo Guedes', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Mason Greenwood', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Neal Maupay', nationality: 'French', position: 'outfield', rarity: 'Common' },
  { name: 'Alexis Sanchez', nationality: 'Chilean', position: 'outfield', rarity: 'Rare' },
  // Eredivisie stars
  { name: 'Brian Brobbey', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Mohamed Kudus', nationality: 'Ghanaian', position: 'outfield', rarity: 'Rare' },
  { name: 'Steven Bergwijn', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Davy Klaassen', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Kenneth Taylor', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Jurrien Timber', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Lisandro Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Antony', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Ryan Gravenberch', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Matthijs de Ligt', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Frenkie de Jong', nationality: 'Dutch', position: 'outfield', rarity: 'Elite' },
  { name: 'Memphis Depay', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Cody Gakpo', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Xavi Simons', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Jorrel Hato', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Sven Botman', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Mats Wieffer', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Quinten Timber', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Tijjani Reijnders', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Cody Gakpo', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  // Primeira Liga
  { name: 'Goncalo Inacio', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Pedro Porro', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Nuno Mendes', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Diogo Dalot', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Palhinha', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Matheus Nunes', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Goncalo Guedes', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Rafael Leao', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Goncalo Ramos', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Felix', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Vitinha', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Fabricio Diaz', nationality: 'Uruguayan', position: 'outfield', rarity: 'Rare' },
  { name: 'Goncalo Guedes', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Francisco Conceicao', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Pedro Neto', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Nuno Tavares', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Tiago Djalo', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Goncalo Ramos', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Neves', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Diogo Costa', nationality: 'Portuguese', position: 'goalkeeper', rarity: 'Rare' },
  // MLS stars
  { name: 'Lionel Messi', nationality: 'Argentine', position: 'outfield', rarity: 'Legendary' },
  { name: 'Luis Suarez', nationality: 'Uruguayan', position: 'outfield', rarity: 'Rare' },
  { name: 'Jordi Alba', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Sergio Busquets', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Sergio Ramos', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Hugo Lloris', nationality: 'French', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Olivier Giroud', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Giorgio Chiellini', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Carlos Vela', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Chicharito', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Gareth Bale', nationality: 'Welsh', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Benzema', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Nani', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Riqui Puig', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Ravel Morrison', nationality: 'Jamaican', position: 'outfield', rarity: 'Rare' },
  { name: 'Gabriel Pires', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Jose Closedo', nationality: 'Mexican', position: 'outfield', rarity: 'Rare' },
  { name: 'Luciano Acosta', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Hany Mukhtar', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Denis Bouanga', nationality: 'Gabonese', position: 'outfield', rarity: 'Rare' },
  // Saudi Pro League
  { name: 'Neymar Jr', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Karim Benzema', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'N\'Golo Kante', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Riyad Mahrez', nationality: 'Algerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sadio Mane', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Roberto Firmino', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Benzema', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Cristiano Ronaldo', nationality: 'Portuguese', position: 'outfield', rarity: 'Legendary' },
  { name: 'Marcelo Brozovic', nationality: 'Croatian', position: 'outfield', rarity: 'Rare' },
  { name: 'Alex Telles', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'David Ospina', nationality: 'Colombian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Edouard Mendy', nationality: 'Senegalese', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Kalidou Koulibaly', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Aymeric Laporte', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Aleksandar Mitrovic', nationality: 'Serbian', position: 'outfield', rarity: 'Rare' },
  { name: 'Allan Saint-Maximin', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Henri Saviet', nationality: 'Gabonese', position: 'outfield', rarity: 'Rare' },
  { name: 'Ruben Neves', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Joao Cancelo', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  { name: 'Otavio', nationality: 'Portuguese', position: 'outfield', rarity: 'Rare' },
  // South American internationals
  { name: 'Lautaro Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Julian Alvarez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Paulo Dybala', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Angel Di Maria', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolas Otamendi', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Lisandro Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Cristian Romero', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Nahuel Molina', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Rodrigo De Paul', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Leandro Paredes', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Enzo Fernandez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Alexis Mac Allister', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Thiago Almada', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Valentin Carboni', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Nico Paz', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Brazilian Ronaldinho', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Casemiro', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Fabinho', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Allan', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Bruno Guimaraes', nationality: 'Brazilian', position: 'outfield', rarity: 'Elite' },
  { name: 'Lucas Paqueta', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Philippe Coutinho', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Roberto Firmino', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Gabriel Jesus', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Richarlison', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Raphinha', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Antony', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Vinicius Junior', nationality: 'Brazilian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Rodrygo', nationality: 'Brazilian', position: 'outfield', rarity: 'Elite' },
  { name: 'Endrick', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Savio', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Estevao', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  // More African stars
  { name: 'Sadio Mane', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Mohamed Salah', nationality: 'Egyptian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Riyad Mahrez', nationality: 'Algerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Youssef En-Nesyri', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Achraf Hakimi', nationality: 'Moroccan', position: 'outfield', rarity: 'Elite' },
  { name: 'Hakim Ziyech', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Noussair Mazraoui', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Nayef Aguerd', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Romain Saiss', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Azzedine Ounahi', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Sofyan Amrabat', nationality: 'Moroccan', position: 'outfield', rarity: 'Rare' },
  { name: 'Andre Onana', nationality: 'Cameroonian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Eric Maxim Choupo-Moting', nationality: 'Cameroonian', position: 'outfield', rarity: 'Rare' },
  { name: 'Vincent Aboubakar', nationality: 'Cameroonian', position: 'outfield', rarity: 'Rare' },
  { name: 'Karl Toko Ekambi', nationality: 'Cameroonian', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolas Pepe', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Wilfried Zaha', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sebastien Haller', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Jonathan Bamba', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Simon Adingra', nationality: 'Ivorian', position: 'outfield', rarity: 'Rare' },
  { name: 'Omar Marmoush', nationality: 'Egyptian', position: 'outfield', rarity: 'Rare' },
  { name: 'Mohamed Elneny', nationality: 'Egyptian', position: 'outfield', rarity: 'Rare' },
  { name: 'Treviso Segzi', nationality: 'Egyptian', position: 'outfield', rarity: 'Rare' },
  { name: 'Victor Osimhen', nationality: 'Nigerian', position: 'outfield', rarity: 'Elite' },
  { name: 'Samuel Chukwueze', nationality: 'Nigerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Ademola Lookman', nationality: 'Nigerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Kelechi Iheanacho', nationality: 'Nigerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Taiwo Awoniyi', nationality: 'Nigerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Wilfred Ndidi', nationality: 'Nigerian', position: 'outfield', rarity: 'Rare' },
  { name: 'Alex Iwobi', nationality: 'Nigerian', position: 'outfield', rarity: 'Rare' },
  // Asian stars
  { name: 'Son Heung-min', nationality: 'South Korean', position: 'outfield', rarity: 'Elite' },
  { name: 'Hwang Hee-chan', nationality: 'South Korean', position: 'outfield', rarity: 'Rare' },
  { name: 'Lee Kang-in', nationality: 'South Korean', position: 'outfield', rarity: 'Rare' },
  { name: 'Kim Min-jae', nationality: 'South Korean', position: 'outfield', rarity: 'Rare' },
  { name: 'Cho Gue-sung', nationality: 'South Korean', position: 'outfield', rarity: 'Rare' },
  { name: 'Takumi Minamino', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Kaoru Mitoma', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Takefusa Kubo', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Daichi Kamada', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Wataru Endo', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Ritsu Doan', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Junya Ito', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Ao Tanaka', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Keito Nakamura', nationality: 'Japanese', position: 'outfield', rarity: 'Rare' },
  { name: 'Yuto Nagatomo', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Maya Yoshida', nationality: 'Japanese', position: 'outfield', rarity: 'Common' },
  { name: 'Alireza Jahanbakhsh', nationality: 'Iranian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sardar Azmoun', nationality: 'Iranian', position: 'outfield', rarity: 'Rare' },
  { name: 'Mehdi Taremi', nationality: 'Iranian', position: 'outfield', rarity: 'Rare' },
  { name: 'Sunil Chhetri', nationality: 'Indian', position: 'outfield', rarity: 'Common' },
  // Youth prospects
  { name: 'Lamine Yamal', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Pau Cubarsi', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Gavi', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Pedri', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Nico Williams', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Florian Wirtz', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Jamal Musiala', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Youssoufa Moukoko', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Mathys Tel', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Warren Zaire-Emery', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Bradley Barcola', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Kobbie Mainoo', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Cole Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Jude Bellingham', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bukayo Saka', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Phil Foden', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Endrick', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Estevao', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Savio', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Matheus Nascimento', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  // More European players
  { name: 'Marcus Thuram', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Randal Kolo Muani', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ousmane Dembele', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Kingsley Coman', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Antoine Griezmann', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Olivier Giroud', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Benzema', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Hugo Lloris', nationality: 'French', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Mike Maignan', nationality: 'French', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Alphonse Areola', nationality: 'French', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Steve Mandanda', nationality: 'French', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Theo Hernandez', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ferland Mendy', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Lucas Digne', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Benjamin Pavard', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Dayot Upamecano', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ibrahima Konate', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Jules Kounde', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Raphael Varane', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Adrien Rabiot', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Aurelien Tchouameni', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Eduardo Camavinga', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Ousmane Dembele', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Kingsley Coman', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Antoine Griezmann', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Olivier Giroud', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Karim Benzema', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Hugo Lloris', nationality: 'French', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Mike Maignan', nationality: 'French', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Alphonse Areola', nationality: 'French', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Steve Mandanda', nationality: 'French', position: 'goalkeeper', rarity: 'Common' },
  { name: 'Theo Hernandez', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ferland Mendy', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Lucas Digne', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Benjamin Pavard', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Dayot Upamecano', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Ibrahima Konate', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Jules Kounde', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Raphael Varane', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Adrien Rabiot', nationality: 'French', position: 'outfield', rarity: 'Rare' },
  { name: 'Aurelien Tchouameni', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Eduardo Camavinga', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  // More Premier League depth
  { name: 'Conor Gallagher', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Mason Mount', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'James Maddison', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Jack Grealish', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Raheem Sterling', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Marcus Rashford', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Phil Foden', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Bukayo Saka', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Cole Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Ollie Watkins', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Alexander Isak', nationality: 'Swedish', position: 'outfield', rarity: 'Elite' },
  { name: 'Darwin Nunez', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Evan Ferguson', nationality: 'Irish', position: 'outfield', rarity: 'Rare' },
  { name: 'Nicolas Jackson', nationality: 'Senegalese', position: 'outfield', rarity: 'Rare' },
  { name: 'Dominic Solanke', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Callum Wilson', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Chris Wood', nationality: 'New Zealander', position: 'outfield', rarity: 'Common' },
  { name: 'Jean-Philippe Mateta', nationality: 'French', position: 'outfield', rarity: 'Common' },
  { name: 'Joao Pedro', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Danny Ings', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  // More midfielders
  { name: 'Rodri', nationality: 'Spanish', position: 'outfield', rarity: 'Legendary' },
  { name: 'Kevin De Bruyne', nationality: 'Belgian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Bernardo Silva', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Bruno Fernandes', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Martin Odegaard', nationality: 'Norwegian', position: 'outfield', rarity: 'Elite' },
  { name: 'Declan Rice', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Enzo Fernandez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Moises Caicedo', nationality: 'Ecuadorian', position: 'outfield', rarity: 'Elite' },
  { name: 'Nicolo Barella', nationality: 'Italian', position: 'outfield', rarity: 'Elite' },
  { name: 'Federico Valverde', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Luka Modric', nationality: 'Croatian', position: 'outfield', rarity: 'Elite' },
  { name: 'Toni Kroos', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Joshua Kimmich', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  { name: 'Frenkie de Jong', nationality: 'Dutch', position: 'outfield', rarity: 'Elite' },
  { name: 'Ilkay Gundogan', nationality: 'German', position: 'outfield', rarity: 'Rare' },
  { name: 'Thiago Alcantara', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Pedri', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Gavi', nationality: 'Spanish', position: 'outfield', rarity: 'Elite' },
  { name: 'Jude Bellingham', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Florian Wirtz', nationality: 'German', position: 'outfield', rarity: 'Elite' },
  // More defenders
  { name: 'Virgil van Dijk', nationality: 'Dutch', position: 'outfield', rarity: 'Legendary' },
  { name: 'Ruben Dias', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'William Saliba', nationality: 'French', position: 'outfield', rarity: 'Elite' },
  { name: 'Gabriel Magalhaes', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'Josko Gvardiol', nationality: 'Croatian', position: 'outfield', rarity: 'Elite' },
  { name: 'Lisandro Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Marc Guehi', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Levi Colwill', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Trent Alexander-Arnold', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Andrew Robertson', nationality: 'Scottish', position: 'outfield', rarity: 'Rare' },
  { name: 'Kyle Walker', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Ben Chilwell', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Luke Shaw', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Trent Alexander-Arnold', nationality: 'English', position: 'outfield', rarity: 'Elite' },
  { name: 'Pedro Porro', nationality: 'Spanish', position: 'outfield', rarity: 'Rare' },
  { name: 'Destiny Udogie', nationality: 'Italian', position: 'outfield', rarity: 'Rare' },
  { name: 'Micky van de Ven', nationality: 'Dutch', position: 'outfield', rarity: 'Rare' },
  { name: 'Cristian Romero', nationality: 'Argentine', position: 'outfield', rarity: 'Rare' },
  { name: 'Kim Min-jae', nationality: 'South Korean', position: 'outfield', rarity: 'Rare' },
  { name: 'Eder Militao', nationality: 'Brazilian', position: 'outfield', rarity: 'Rare' },
  { name: 'David Alaba', nationality: 'Austrian', position: 'outfield', rarity: 'Rare' },
  // More goalkeepers
  { name: 'Alisson Becker', nationality: 'Brazilian', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Ederson', nationality: 'Brazilian', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Andre Onana', nationality: 'Cameroonian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'David Raya', nationality: 'Spanish', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Guglielmo Vicario', nationality: 'Italian', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Jordan Pickford', nationality: 'English', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Emiliano Martinez', nationality: 'Argentine', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Yann Sommer', nationality: 'Swiss', position: 'goalkeeper', rarity: 'Rare' },
  { name: 'Mike Maignan', nationality: 'French', position: 'goalkeeper', rarity: 'Elite' },
  { name: 'Gianluigi Donnarumma', nationality: 'Italian', position: 'goalkeeper', rarity: 'Elite' },
  // More strikers
  { name: 'Erling Haaland', nationality: 'Norwegian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Kylian Mbappe', nationality: 'French', position: 'outfield', rarity: 'Legendary' },
  { name: 'Harry Kane', nationality: 'English', position: 'outfield', rarity: 'Legendary' },
  { name: 'Robert Lewandowski', nationality: 'Polish', position: 'outfield', rarity: 'Elite' },
  { name: 'Mohamed Salah', nationality: 'Egyptian', position: 'outfield', rarity: 'Legendary' },
  { name: 'Son Heung-min', nationality: 'South Korean', position: 'outfield', rarity: 'Elite' },
  { name: 'Victor Osimhen', nationality: 'Nigerian', position: 'outfield', rarity: 'Elite' },
  { name: 'Lautaro Martinez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Rafael Leao', nationality: 'Portuguese', position: 'outfield', rarity: 'Elite' },
  { name: 'Dusan Vlahovic', nationality: 'Serbian', position: 'outfield', rarity: 'Elite' },
  { name: 'Alexander Isak', nationality: 'Swedish', position: 'outfield', rarity: 'Elite' },
  { name: 'Darwin Nunez', nationality: 'Uruguayan', position: 'outfield', rarity: 'Elite' },
  { name: 'Julian Alvarez', nationality: 'Argentine', position: 'outfield', rarity: 'Elite' },
  { name: 'Ollie Watkins', nationality: 'English', position: 'outfield', rarity: 'Rare' },
  { name: 'Cole Palmer', nationality: 'English', position: 'outfield', rarity: 'Elite' },
];

async function seedRealPlayers() {
  await connectDB();
  
  console.log('Seeding 1000 real football players into the market...');
  
  let seeded = 0;
  for (const playerData of REAL_PLAYERS) {
    if (seeded >= 1000) break;
    
    // Create player in the players table
    const player = Player.create({
      ownerId: 'AI_MARKET',
      name: playerData.name,
      role: playerData.position,
      rarity: playerData.rarity,
      nationality: playerData.nationality,
      stats: generateStats(playerData.position, playerData.rarity),
    });
    
    // Calculate market value
    const value = Player.marketValue(player);
    const price = Math.round(value * (0.8 + Math.random() * 0.4)); // 80-120% of value
    
    // List on market
    db.insert(MARKET_TABLE, player.id, {
      id: player.id,
      playerId: player.id,
      sellerId: 'AI_MARKET',
      sellerName: 'AI Market',
      price,
      listedAt: new Date().toISOString(),
      expiresAt: null,
      sold: false,
    });
    
    seeded++;
    if (seeded % 100 === 0) {
      console.log(`Seeded ${seeded} players...`);
    }
  }
  
  console.log(`Done! Seeded ${seeded} real football players into the market.`);
}

function generateStats(role, rarity) {
  const base = rarity === 'Legendary' ? 85 : rarity === 'Elite' ? 75 : rarity === 'Rare' ? 65 : 55;
  const variance = 10;
  
  if (role === 'goalkeeper') {
    return {
      reflex: base + Math.floor(Math.random() * variance),
      positioning: base + Math.floor(Math.random() * variance),
      anticipation: base + Math.floor(Math.random() * variance),
      strength: base + Math.floor(Math.random() * variance),
      composure: base + Math.floor(Math.random() * variance),
    };
  }
  
  return {
    pace: base + Math.floor(Math.random() * variance),
    skill: base + Math.floor(Math.random() * variance),
    shooting: base + Math.floor(Math.random() * variance),
    stamina: base + Math.floor(Math.random() * variance),
    composure: base + Math.floor(Math.random() * variance),
  };
}

seedRealPlayers().catch(console.error);
