const fs=require('fs'),os=require('os'),path=require('path');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'vt-loan-'));
const {MODERATION}=require('./config/constants'); MODERATION.COOLDOWN_MS=0; MODERATION.WARNINGS_BEFORE_BAN=9999;
const m=require('./utils/messaging'); m.smartTypingPause=async()=>{};
const db=require('./config/database'); const User=require('./models/User');
const {grantStarterSquad}=require('./utils/playerGenerator'); const router=require('./commands/router');
const A='1111111111@s.whatsapp.net', B='2222222222@s.whatsapp.net';
const sent=[]; const sock={sendMessage:async(j,c)=>{sent.push(c);return{};},sendPresenceUpdate:async()=>{},groupMetadata:async()=>({desc:'',subject:'T'})};
const clean=t=>String(t).replace(/[\u200B-\u200F\u2060-\u2064\uFEFF\u034F\u17B5\u180E]/g,'');
const mk=(t,s)=>({key:{remoteJid:s,participant:s,fromMe:false},message:{conversation:t}});
async function run(t,s){sent.length=0;await router.handle(sock,mk(t,s));return clean(sent.map(x=>x.text||'').join('\n'));}
let pass=0,fail=0; const ok=(l,c,d)=>{c?(console.log('  ✓ '+l),pass++):(console.log('  ✗ '+l+(d?' — '+d:'')),fail++);};
(async()=>{await db.connectDB();
User.create(A,'Alpha');grantStarterSquad(A);User.update(A,{registered:true,currency:80000});
User.create(B,'Beta');grantStarterSquad(B);User.update(B,{registered:true,currency:80000});
console.log('\nARGUMENT ORDER SHOULD NOT MATTER');
let o=await run('!borrow 5000 Beta',A);
ok('amount-then-name works', /LOAN REQUEST|request|Beta/i.test(o), o.slice(0,70));
const id1=(o.match(/mloan_[a-z0-9_]+/)||[])[0];
ok('a loan id was issued', !!id1, o.slice(0,90));
o=await run('!borrow Beta 7000',A);
ok('name-then-amount works', /mloan_/.test(o), o.slice(0,70));
console.log('\nDEFAULT TERM');
ok('defaults to 7 days not 1', /7 day|in 7/i.test(o), o.slice(0,120));
console.log('\nTHE OPPOSITE DIRECTION NOW EXISTS');
o=await run('!lend Beta 9000',A);
ok('!lend offers money', /LOAN OFFERED/i.test(o), o.slice(0,70));
const id2=(o.match(/mloan_[a-z0-9_]+/)||[])[0];
ok('!lend issues an id', !!id2);
console.log('\nTHE RIGHT PERSON ACCEPTS');
o=await run('!loan accept '+id2, A);
ok('lender cannot accept their own offer', /isn't yours to accept/i.test(o), o.slice(0,70));
const bBefore=User.getByWhatsappId(B).currency;
o=await run('!loan accept '+id2, B);
ok('borrower can accept it', /APPROVED/i.test(o), o.slice(0,80));
ok('money actually moved', User.getByWhatsappId(B).currency > bBefore,
   `before ${bBefore}, after ${User.getByWhatsappId(B).currency}`);
console.log('\nPLAIN LANGUAGE');
o=await run('!loan money',A);
ok('help says ASK, not LEND', /ASK SOMEONE FOR A LOAN/i.test(o), o.slice(0,60));
ok('help shows both directions', /!lend/.test(o));
o=await run('!lend',A);
ok('!lend explains itself', /LEND MONEY/i.test(o), o.slice(0,60));
console.log('\n'+'='.repeat(46));
console.log(`LOAN UX TESTS: ${pass} passed, ${fail} failed`);
console.log('='.repeat(46));
process.exit(fail?1:0);})();
