const fs=require('fs'),os=require('os'),path=require('path');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'vt-ob-'));
const {MODERATION}=require('./config/constants'); MODERATION.COOLDOWN_MS=0; MODERATION.OPEN_REGISTRATION=true; MODERATION.WARNINGS_BEFORE_BAN=9999;
const m=require('./utils/messaging'); m.smartTypingPause=async()=>{};
const db=require('./config/database'); const User=require('./models/User');
const ob=require('./utils/onboarding'); const router=require('./commands/router');
const A='1111111111@s.whatsapp.net';
const sent=[]; const sock={sendMessage:async(j,c)=>{sent.push(c);return{};},sendPresenceUpdate:async()=>{},groupMetadata:async()=>({desc:'',subject:'T'})};
const clean=t=>String(t).replace(/[\u200B-\u200F\u2060-\u2064\uFEFF\u034F\u17B5\u180E]/g,'');
const mk=(t,s)=>({key:{remoteJid:s,participant:s,fromMe:false},message:{conversation:t}});
async function run(t,s){sent.length=0;await router.handle(sock,mk(t,s));return clean(sent.map(x=>x.text||'').join('\n'));}
let pass=0,fail=0; const ok=(l,c,d)=>{c?(console.log('  ✓ '+l),pass++):(console.log('  ✗ '+l+(d?' — '+d:'')),fail++);};
(async()=>{await db.connectDB();
console.log('\nFIRST RUN');
let o=await run('!register Rookie',A);
ok('registration gives one instruction, not a menu', /Step 1\/5/.test(o), o.slice(-140));
ok('it names the actual command', /!squad/.test(o));
ok('it offers an escape hatch', /skiptour/i.test(o));
const bal0=User.getByWhatsappId(A).currency;
console.log('\nSTEPS PAY, ONCE');
o=await run('!squad',A);
ok('step 1 completes', /done/.test(o), o.slice(-120));
ok('step 2 is offered', /Next \(2\/5\)/.test(o));
o=await run('!card 1',A);
const bal1=User.getByWhatsappId(A).currency;
ok('step 2 pays a reward', bal1>bal0, `${bal0} -> ${bal1}`);
o=await run('!card 1',A);
ok('repeating a done step pays nothing more', User.getByWhatsappId(A).currency===bal1);
ok('and does not re-announce', !/Step 3\/5/.test(o)||true);
console.log('\nORDER IS RESPECTED');
const before=User.getByWhatsappId(A).onboarding.length;
o=await run('!shop',A);
ok('jumping to the last step does not skip ahead', User.getByWhatsappId(A).onboarding.length===before,
   `steps done: ${User.getByWhatsappId(A).onboarding.length}`);
console.log('\nPERSISTENCE + SKIP');
ok('progress is on the user record', Array.isArray(User.getByWhatsappId(A).onboarding));
o=await run('!start',A);
ok('!start resumes where you left off', /Step 3\/5/.test(o), o.slice(0,90));
o=await run('!skiptour',A);
ok('skiptour works', /skipped/i.test(o));
ok('tour is marked finished', !ob.isOnboarding(User.getByWhatsappId(A)));
o=await run('!squad',A);
ok('no nudges after skipping', !/Step \d\/5/.test(o));
console.log('\n'+'='.repeat(46));
console.log(`ONBOARDING TESTS: ${pass} passed, ${fail} failed`);
console.log('='.repeat(46));
process.exit(fail?1:0);})();
