// game-engine/commentaryGenZ.js
// Gen Z flavor-text pack — single-line commentary bits for moments the base
// SEQUENCES in commentary.js don't cover: buildup play, defensive actions,
// pressure/tension, turnovers, and crowd/hype reactions.
//
// Use like: pick(GEN_Z.BUILDUP).replace(/{player}/g, name).replace(/{team}/g, team)
// Drop these in mid-burst as connective tissue between the main SEQUENCES lines,
// or use standalone for minor events that don't need a full 3-message burst.

const { pick } = require('../utils/random');

const GEN_Z = {

  // ─── BUILDUP — working the ball from the back, patient possession ────────
  BUILDUP: [
    '{team} building from the back, no cap, real patient right now 🧠',
    '{player} switching the play like he\'s got 20/20 vision fr',
    'this buildup is CLEAN, {team} not rushing a thing 😮\u200d💨',
    '{player} playing chess while everyone else plays checkers ♟️',
    'the tempo just changed, {team} found their rhythm fr fr',
    '{player} threading it through the lines like it\'s nothing 🧵',
    'slow it down, speed it up — {team} controlling the whole vibe rn',
    '{player} scanning before he even gets the ball, that\'s the difference 👀',
    'phase of play looking crispy from {team} ngl',
    '{player} with the calm touch, zero panic in his game 😤',
    'this is patient build up and I\'m HERE for it 🍿',
    '{team} moving it side to side, waiting for the gap to open up',
    '{player} dropped deep to collect it, bro\'s basically the quarterback now 🏈',
    'every pass got a purpose right now, {team} on one',
    '{player} one-touch, two-touch, clean as it gets fr',
    'the buildup play is giving main character energy ngl',
    '{team} stringing passes together like it\'s a training drill 📐',
    '{player} not forcing it, letting the game come to him, respect',
    'this possession sequence is elite, {team} cooking slowly 🍳',
    '{player} rolled his man with one touch, didn\'t even look up 😮\u200d💨',
    'buildup so smooth you could pour syrup on it 🥞',
    '{team} recycling possession, resetting, no rush at all',
    '{player} spotted the switch early, ball\'s already gone 🛰️',
    'that\'s a proper progressive pass from {player}, splitting lines',
    '{team} in control of the tempo, and everybody knows it',
    '{player} shielding it, waiting for support, textbook stuff',
    'the patience here is actually kinda scary, {team} not blinking',
    '{player} playing it simple, playing it smart, IQ off the charts 🧠',
    'this is that composed, grown-man buildup right there',
    '{team} pulling the defense apart one pass at a time, slowly',
    '{player} got time on the ball and he KNOWS it 😌',
    'clean carry from {player}, nobody\'s closing him down yet',
    'the shape {team} is playing in right now? chef\'s kiss 👨\u200d🍳',
    '{player} disguised that pass so well, defender bought it completely',
    'buildup play looking like a highlight reel already, we ain\'t even shot yet',
    '{team} just baiting the press right now, watch this',
    '{player} rolled it back to reset, smart, no need to force anything',
    'this is slow-cooked football and {team} is the chef 🔥',
    '{player} playing it under pressure like it\'s a friendly, ice in his veins 🧊',
    'the ball is moving faster than the players right now, {team} clicking',
    '{player} with the disguised through-ball, that\'s SPECIAL',
    'buildup this clean should honestly be studied in film sessions',
    '{team} not panicking even with bodies around them, mentality different',
    '{player} playing out from the back, brave decision, paying off so far',
    'this passing sequence just broke three lines, {team} surgical rn',
    '{player} really said "watch this" with that first touch',
    'the way {team} is circulating this ball is borderline disrespectful',
    '{player} controlling tempo like he owns the pitch, no cap',
    'buildup play THIS composed under pressure? that\'s different gravy',
    '{team} playing keep-away and making it look effortless',
  ],

  // ─── DEFENSE — tackles, blocks, discipline, last-ditch stuff ─────────────
  DEFENSE: [
    '{player} not letting NOTHING through, that\'s a wall right there 🧱',
    'that\'s a certified DEFENSIVE MASTERCLASS from {player} 😤',
    '{player} read that like he wrote the script, intercepted with ease',
    'nah {player} really said "not today" and cleared it 🚫',
    'that block from {player} was diff, took one for the team fr',
    '{team} defending like their whole life depends on it rn',
    '{player} tracked that run the ENTIRE way, discipline elite',
    'that\'s a last-ditch tackle from {player}, absolute hero ball 🦸',
    '{player} won that duel clean, no fouls, just pure defending',
    'the recovery run from {player} was actually insane, caught him up',
    '{team} at the back is locked in right now, nothing getting past',
    '{player} timed that challenge PERFECTLY, textbook tackle',
    'that\'s a header clearance from {player}, sent it back to row Z 🚀',
    '{player} standing his ground, didn\'t dive in, smart defending',
    'the concentration from {team}\'s backline is unmatched today',
    '{player} closed the passing lane before the pass even happened 🔒',
    'that\'s organized chaos and {team} thriving in it defensively',
    '{player} sliding tackle, won the ball clean, zero contact on the man',
    '{team} defending as a UNIT right now, shape is immaculate',
    '{player} put his body on the line for that block, respect due 🫡',
    'nah the anticipation from {player} on that interception was crazy',
    '{player} shut that down before it even started, elite reading of the game',
    'that\'s a goal-saving block, {player} out here being the difference',
    '{team} not giving an inch back there, fortress mode activated 🏰',
    '{player} muscled him off the ball, strength different',
    'the covering run from {player} bailed his teammate out completely',
    '{player} stood him up, made him go backwards, defending 101',
    'that\'s a professional foul if I\'ve ever seen one, {player} took it',
    '{team}\'s defensive line moving in sync like it\'s choreographed',
    '{player} won that header even though he\'s giving up inches, heart 💯',
    'the recovery pace on {player} is not normal, caught a runner from nowhere',
    '{player} bodied his man off the ball, didn\'t even need the tackle',
    'that\'s a clean sheet mentality from {team} right now, nobody\'s scoring',
    '{player} read the through ball before it was even played, IQ',
    'the discipline to not dive in there from {player}? mature defending',
    '{team} squeezing the pitch so tight there\'s nowhere left to go',
    '{player} came out of nowhere for that tackle, where\'d he even come from 😭',
    'that\'s a rock-solid partnership at the back for {team} right now',
    '{player} nutmegged the striker on the way OUT, defending with flair',
    'the block from {player} genuinely might\'ve saved a goal there',
    '{team} defending deep and compact, patient, waiting to strike',
    '{player} put in a shift there, covered every blade of grass',
    'that\'s a header away to safety from {player}, no messing about',
    '{player} tracked back 60 yards for that tackle, work rate insane',
    'the timing on that slide tackle from {player} was surgical',
    '{team} not rattled at all, defending with composure under pressure',
    '{player} shepherded that ball out for a goal kick, zero risk taken',
    'that interception from {player} basically started the counter, huge',
    '{team} making it look easy back there but that\'s elite level defending',
    '{player} stayed on his feet, didn\'t dive, forced the error instead',
  ],

  // ─── PRESSURE — high press, squeezing, forcing panic ─────────────────────
  PRESSURE: [
    '{team} pressing like their lives depend on it right now 😤',
    '{player} closing down so fast the defender panicked mid-touch',
    'the press is SUFFOCATING, {team} not giving a second on the ball',
    '{player} won that ball back off pure pressure alone, no tackle needed',
    'you can feel the panic setting in, {team}\'s press is relentless',
    '{player} hunting in packs with his teammates, coordinated pressure',
    'that\'s forced turnover #3 from {team}\'s press this half',
    '{player} closed the angle so quick the pass had nowhere to go',
    'the intensity from {team} right now is genuinely different gravy',
    '{player} pressed him into a mistake, that\'s exactly the plan working',
    '{team} squeezing the pitch, cutting off every single option',
    'nah {player} chased that ball down like it owed him money 🏃',
    'the press is ON, {team} not letting them breathe for one second',
    '{player} forced the back pass, mission accomplished right there',
    'that\'s high-press football executed perfectly by {team}',
    '{player} won it back within three seconds of losing it, elite counter-press',
    'the defender is RATTLED, {team}\'s pressure getting to him',
    '{player} closing down space like the pitch just got smaller',
    'that turnover was forced, pure and simple, {team} suffocating them',
    '{player} not giving him time to even THINK on the ball',
    '{team} pressing as a five, nobody\'s got an easy pass right now',
    'the panic in that clearance says everything about {team}\'s press',
    '{player} sprinting 40 yards just to close down a throw-in, mentality',
    'that\'s textbook counter-press, won it back in the danger zone',
    '{team} not letting them settle for even a single second',
    '{player} forced a wild clearance, straight out of bounds, chaos created',
    'the press-trigger from {team} was perfect, timed it exactly right',
    '{player} closing every passing lane, defender had nowhere to go',
    'that\'s a gegenpress masterclass from {team} right now, relentless',
    '{player} won the ball high up the pitch, that\'s dangerous territory now',
    'the energy on this press is unreal, {team} sprinting in numbers',
    '{player} pressured him into an underhit pass, easy pickings now',
    '{team} hunting the ball like a pack, nobody\'s comfortable on it',
    'that\'s the third giveaway forced by {team}\'s press this half',
    '{player} closed him down so fast he had to just boot it away',
    'the pressure is mounting, you can see {team} sensing blood right now',
    '{player} not letting the goalkeeper have an easy pass out either',
    'that\'s aggressive, coordinated pressing from {team}, well drilled',
    '{player} forced the error high up, immediate transition opportunity',
    'the press is breaking {team}\'s opponent down mentally at this point',
    '{player} closed the space before the ball even arrived, anticipation',
    'that\'s a trap sprung perfectly, {team} baited him into the press',
    '{player} sprinting back to press even after the attack broke down',
    'the intensity from {team} hasn\'t dropped for one single minute',
    '{player} won it back inside the box off pure pressure, huge moment',
    'that\'s relentless, {team} suffocating every single outlet',
    '{player} closed him down two-on-one, ball had nowhere safe to go',
    'the press just forced a corner, {team}\'s intensity paying off',
    '{player} not giving an inch, chasing lost causes and winning them',
    'that\'s championship-level pressing from {team} right there, no cap',
  ],

  // ─── TURNOVER — winning the ball, interceptions, transitions ─────────────
  TURNOVER: [
    '{player} picked that pocket clean, didn\'t even foul him 🧤',
    'TURNOVER! {player} sniffed that pass out before it even happened',
    '{player} stole it right off his toes, that\'s disrespectful ngl',
    'possession changes hands, {player} snapped it up instantly',
    'that\'s a jailbreak, {player} won it and they\'re already sprinting 🏃',
    '{player} intercepted that like he had the cheat codes 🎮',
    'quick hands from {player}, turnover, and now it\'s three-on-two',
    '{player} read the pass, stepped in front, ball\'s gone the other way',
    'that\'s a costly giveaway, {player} punished it instantly',
    '{player} won the ball and it\'s an instant counter-attack now 🚨',
    'sloppy pass, {player} was already moving before it left his foot',
    '{player} intercepted, one touch, and he\'s already looking forward',
    'that\'s exactly the kind of turnover that wins matches, {player} alert',
    '{player} nicked it away so smoothly, barely broke stride',
    'the ball\'s changed hands and {team} smell blood immediately',
    '{player} anticipated the whole thing, turnover complete',
    'that\'s a heavy touch punished IMMEDIATELY by {player}',
    '{player} won it back in a dangerous area, this could hurt them',
    'quick reactions from {player}, snatched it before it even settled',
    'that\'s a turnover in the worst possible area for the opponent',
    '{player} pounced on that loose ball like it was free money 💰',
    'the interception from {player} sparks a three-on-one right now',
    '{player} closed the gap and just took it, simple as that',
    'that giveaway is gonna sting, {player} didn\'t need asking twice',
    '{player} stole possession and immediately played it forward, no hesitation',
    'the transition is ON, {player} won it and they\'re already breaking',
    'that\'s a costly mistake, {player} made them pay instantly',
    '{player} intercepted mid-air, didn\'t even let it bounce',
    'possession lost, possession gained, {player} capitalized right away',
    '{player} read the body language and jumped the passing lane',
    'that\'s how you punish a lazy pass, {player} all over it',
    'the turnover happened so fast half the stadium missed it',
    '{player} won it in a phone booth, tight space, still came out clean',
    'that interception basically ended the attack before it started',
    '{player} snatched it and now it\'s a foot race the other way 💨',
    'careless pass, {player} was lurking, turnover complete',
    'the ball\'s gone the other way and {team} are already sprinting forward',
    '{player} won the second ball too, double turnover, ruthless',
    'that\'s a turnover that could genuinely swing this whole match',
    '{player} anticipated it two seconds before anyone else even reacted',
    'quick feet, quicker mind, {player} turned that over instantly',
    'the giveaway is punished, {player} already thinking about the next pass',
    '{player} stepped up, won the ball, and the crowd is UP for it',
    'that\'s a turnover in a really really bad spot for them right now',
    '{player} read the pass like he was told what was coming',
    'the ball changed hands and the whole momentum just flipped',
    '{player} snuffed that out before it even became a real chance',
    'that interception was worth its weight in gold right there',
    '{player} won it back and immediately, IMMEDIATELY looked dangerous',
    'the turnover forces a scramble, nobody\'s organized for {team} now',
  ],

  // ─── HYPE / CROWD — atmosphere, momentum, reactions ───────────────────────
  HYPE: [
    'the crowd is UP, something\'s brewing here fr fr 📢',
    'you can feel the momentum shifting, {team} smell it too',
    'the energy in this match just changed completely, no cap',
    'everybody on the touchline is on their feet right now 🔥',
    'this is the kind of moment that decides matches, tension is real',
    'the atmosphere just went up ten levels, {team} feeding off it',
    'you love to see it, {team} playing with SWAGGER right now',
    'the whole vibe of this match just flipped in like two minutes',
    'that passage of play had everyone on the edge of their seat',
    '{team} is BUILT for moments like this, no fear at all',
    'the tension right now is genuinely unmatched, anything could happen',
    'this is main character energy from {team}, taking the game over',
    'the crowd noise just spiked, they know something\'s coming',
    'that\'s the kind of momentum you can\'t coach, {team} just has it',
    'everyone\'s locked in right now, this match is COOKING 🍳',
    'the belief on {team}\'s faces right now is a whole different level',
    'this game just found another gear and nobody saw it coming',
    'the pressure of this moment is real and {team} is thriving in it',
    'you can hear a pin drop, then BOOM, {team} makes it happen',
    'that\'s the switch flipping, {team} just found their gear',
    'the whole complexion of this match just changed in an instant',
    'this is legacy-defining stuff for whoever comes out on top here',
    '{team} playing with house money right now, nothing to lose energy',
    'the belief is UNREAL right now, {team} feels unstoppable',
    'that\'s the kind of spell that wins championships, {team} in the zone',
    'the tension is thick enough to cut with a knife right now',
    'this match just became must-watch television, no cap',
    '{team} feeding off the energy and it shows in every touch',
    'the momentum swing right here might decide the whole match',
    'you can feel it building, {team} on the verge of something special',
    'that\'s peak drama, this is exactly why we watch this sport',
    'the confidence radiating off {team} right now is contagious',
    'this is the kind of five minutes that gets replayed for years',
    'everybody sensed that shift at the exact same time, electric',
    '{team} playing with zero fear right now, full send energy',
    'the intensity just doubled, this match refuses to calm down',
    'that\'s a statement being made right now by {team}, loud and clear',
    'the crowd is INTO it, feeding {team} every ounce of energy',
    'this is the kind of pressure that separates good from great',
    '{team} smelling blood right now, momentum fully on their side',
    'the whole energy of this match just got turned up to eleven',
    'that shift in momentum was instant, {team} seized it immediately',
    'this is peak tension, every touch feels like it matters right now',
    '{team} riding a wave right now and everybody can feel it',
    'the stadium (or the group chat, let\'s be real) is going CRAZY right now',
    'that\'s the moment belief turned into momentum for {team}',
    'you love to see a team seize a moment like {team} just did',
    'the drama right now is unreal, this is why VOLTA hits different',
    '{team} playing like they know something the rest of us don\'t',
    'this is the energy that turns a good run into a legendary one',
  ],
};

/** Fill a line's {player}/{team} placeholders. */
function fillLine(line, ctx = {}) {
  return line
    .replace(/{player}/g, ctx.player || 'The player')
    .replace(/{team}/g, ctx.team || 'The team');
}

/** Grab a random Gen Z line from a category, filled in with context. */
function genZLine(category, ctx = {}) {
  const pool = GEN_Z[category];
  if (!pool) return '';
  return fillLine(pick(pool), ctx);
}

module.exports = { GEN_Z, fillLine, genZLine };
