// game-engine/situations.js
// 50+ interactive match situations for PvP. Each situation has:
//   build:   buildup commentary lines (sent with delays before the choice)
//   options: the choices the attacking manager can pick (letters a/b/c/d)
//            each option has a goal-weight (gw) used in the chance math
//   goal:    commentary shown when the chance is scored
//   miss:    commentary shown when it's not
// Placeholders: {player} = attacker name, {team} = attacking team, {opp} = defending team.
const { pick } = require('../utils/random');

const SITUATIONS = [
  {
    build: ['🔥 {player} intercepts and is OFF TO THE RACES!', 'Screaming down the wing, one man to beat...',
      'The crowd rises to its feet...',
      'Tension crackles around the box...',
      '{opp} scramble to reorganise...',
      '{team} sense an opening...'],
    options: [
      { key: 'a', label: 'Power Shot', gw: 1.2, aliases: ['shoot', 'shot'] },
      { key: 'b', label: 'Chip', gw: 1.0, aliases: ['chip'] },
      { key: 'c', label: 'Cut Inside', gw: 1.1, aliases: ['cut', 'inside'] },
      { key: 'd', label: 'Cross It', gw: 0.8, aliases: ['cross'] },
    ],
    goal: ['⚽ *GOAL!!* {player} BURIES it top corner! {team} GO MENTAL! 🤯', '💥 *GOAL!* {player} finishes like a pro — {team} explode! 🔥'],
    miss: ['😱 {player} drags it wide! {opp} breathe again...', '🧤 {player} shoots... straight at the keeper! {opp} clear!'],
  },
  {
    build: ['⚡ {team} spring a lightning counter!', '{player} is through on goal with only the keeper to beat!'],
    options: [
      { key: 'a', label: 'Round Keeper', gw: 1.15, aliases: ['round', 'chip'] },
      { key: 'b', label: 'Low Drive', gw: 1.1, aliases: ['drive', 'shot'] },
      { key: 'c', label: 'Panenka', gw: 1.25, aliases: ['panenka'] },
      { key: 'd', label: 'Pass Across', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} dinks it past the keeper — ICE! 🧊', '💥 *GOAL!!* {player} slots it home, {team} are bouncing! 🕺'],
    miss: ['😤 {player} hesitates... keeper smothers it! 🧤', '🚫 {player} tries to round him — keeper stands tall!'],
  },
  {
    build: ['🆓 Free kick on the edge of the box...', '{player} places the ball. The wall lines up.',
      'The wall jumps as one...',
      'The keeper screams for height...',
      'The box is packed tight...',
      '{player} eyes the top corner...'],
    options: [
      { key: 'a', label: 'Over Wall', gw: 1.1, aliases: ['over'] },
      { key: 'b', label: 'Around Wall', gw: 1.05, aliases: ['around', 'curl'] },
      { key: 'c', label: 'Blast At Wall', gw: 0.85, aliases: ['blast'] },
      { key: 'd', label: 'Short Flick', gw: 0.95, aliases: ['short', 'flick'] },
    ],
    goal: ['⚽ *FREE KICK GOAL!* {player} bends it BEAUTIFULLY! 😍', '💥 *GOAL!* {player} catches the keeper napping! 🔥'],
    miss: ['🧱 Blocked by the wall! {opp} hoof it clear!', '😩 {player} curls it just over the bar!'],
  },
  {
    build: ['🚩 Corner coming in...', '{player} ghosts to the near post.',
      'The delivery is whipped in...',
      'Bodies collide in the air...',
      'The keeper hesitates...',
      '{team} hold their breath...'],
    options: [
      { key: 'a', label: 'Glance Header', gw: 1.15, aliases: ['header', 'glance'] },
      { key: 'b', label: 'Flick Back', gw: 1.0, aliases: ['flick', 'back'] },
      { key: 'c', label: 'Volley', gw: 1.2, aliases: ['volley'] },
      { key: 'd', label: 'Wait Outside', gw: 0.85, aliases: ['wait'] },
    ],
    goal: ['⚽ *HEADER! GOAL!!* {player} rises highest! 🦅', '💥 *GOAL!* {player} flicks it in — {team} go wild! 🤩'],
    miss: ['🧤 Keeper claims the corner! {opp} survive!', '😬 {player} mistimes it — over the bar!'],
  },
  {
    build: ['🎯 Penalty awarded! {opp} players fume.', '{player} puts the ball on the spot. Stone cold.',
      'The keeper guesses left...',
      'The whistle blows...',
      '{player} keeps his cool...',
      'The moment stretches forever...'],
    options: [
      { key: 'a', label: 'Power Corner', gw: 1.2, aliases: ['corner', 'power'] },
      { key: 'b', label: 'Panenka', gw: 1.25, aliases: ['panenka', 'chip'] },
      { key: 'c', label: 'Down Middle', gw: 1.1, aliases: ['middle'] },
      { key: 'd', label: 'Dummy', gw: 0.9, aliases: ['dummy'] },
    ],
    goal: ['⚽ *PENALTY SCORED!* {player} sends the keeper the wrong way! 😏', '💥 *GOAL FROM THE SPOT!* {team} celebrate! 🔥'],
    miss: ['🧤 Keeper reads it and SAVES! 🤯', '😩 {player} skies it over the bar! The waste!'],
  },
  {
    build: ['💣 {player} picks it up 30 yards out.', 'Drops a shoulder, winds up...',
      'The netting ripples behind...',
      'The keeper sets his feet...',
      'The crowd leans in...',
      '{opp} brace for impact...'],
    options: [
      { key: 'a', label: 'Thunderbolt', gw: 1.2, aliases: ['shot', 'bolt'] },
      { key: 'b', label: 'Driven Low', gw: 1.1, aliases: ['low', 'drive'] },
      { key: 'c', label: 'Chip From Range', gw: 0.95, aliases: ['chip'] },
      { key: 'd', label: 'Pass Forward', gw: 0.85, aliases: ['pass'] },
    ],
    goal: ['⚽ *WHAT A STRIKE!* {player} absolutely MURDERS it in! 💥', '🌟 *GOAL!* That\'s,goal of the game! {team} lose it! 😤'],
    miss: ['🧱 Cannoned off the bar! {opp} clear the wreckage!', '😱 {player} scuffs it — easy for the keeper.'],
  },
  {
    build: ['🎯 Cross whipped in!', '{player} attacks the ball at the back stick.',
      'The cross is pinpoint...',
      'A defender slides across...',
      'The keeper flaps...',
      '{team} scream for it...'],
    options: [
      { key: 'a', label: 'Bullet Header', gw: 1.2, aliases: ['header'] },
      { key: 'b', label: 'Volley', gw: 1.15, aliases: ['volley'] },
      { key: 'c', label: 'Flick On', gw: 0.95, aliases: ['flick'] },
      { key: 'd', label: 'Control & Turn', gw: 0.9, aliases: ['control'] },
    ],
    goal: ['⚽ *HEADER! GOAL!* {player} powers it past the keeper! 💪', '💥 *GOAL!* {player} volleys home — {team} erupt! 🔥'],
    miss: ['😩 {player} heads it over! So close!', '🧤 Keeper plucks it out the air!'],
  },
  {
    build: ['🌀 {player} twists and turns in the box...', 'Defenders backing off...',
      'The space opens up...',
      '{opp} are worried now...',
      'The crowd urges him on...',
      '{team} sense weakness...'],
    options: [
      { key: 'a', label: 'Nutmeg', gw: 1.1, aliases: ['nutmeg', 'meg'] },
      { key: 'b', label: 'Stepover Shot', gw: 1.15, aliases: ['shot', 'stepover'] },
      { key: 'c', label: 'Elastico', gw: 1.05, aliases: ['elastico'] },
      { key: 'd', label: 'Backheel', gw: 0.95, aliases: ['backheel'] },
    ],
    goal: ['⚽ *GOAL!* {player} NUTMEGS the defender and finishes! 😂', '💥 *GOAL!!* Filthy skill from {player} — {team} go crazy! 🔥'],
    miss: ['🔄 {player} loses it in the shuffle — cleared!', '😤 {player} tries the fancy stuff — tackled!'],
  },
  {
    build: ['⚡ {team} play it out from the back.', '{player} receives in acres of space...',
      'The pitch opens ahead...',
      '{opp} drop deep...',
      'The tempo quickens...',
      '{team} sense a break...'],
    options: [
      { key: 'a', label: 'Through Ball', gw: 1.05, aliases: ['through', 'pass'] },
      { key: 'b', label: 'Surge Forward', gw: 1.1, aliases: ['surge', 'run'] },
      { key: 'c', label: 'Switch Play', gw: 0.9, aliases: ['switch'] },
      { key: 'd', label: 'Shoot From Deep', gw: 1.0, aliases: ['shot'] },
    ],
    goal: ['⚽ *GOAL!* {player} releases the perfect pass then finishes! 🎯', '💥 *GOAL!* {player} drives into the box and scores! 🔥'],
    miss: ['🔄 {player} overhits the pass — offside flag! 🚩', '😱 {player} crowded out — {opp} win it back.'],
  },
  {
    build: ['🍫 {player} lines up the chip...', 'Keeper is off his line...'],
    options: [
      { key: 'a', label: 'Delicate Chip', gw: 1.2, aliases: ['chip'] },
      { key: 'b', label: 'Place It', gw: 1.1, aliases: ['place'] },
      { key: 'c', label: 'Lob Volley', gw: 1.15, aliases: ['lob', 'volley'] },
      { key: 'd', label: 'Roll It', gw: 0.95, aliases: ['roll'] },
    ],
    goal: ['⚽ *CHIPPED! GOAL!* {player} lobs it over the keeper! 😍', '💥 *GOAL!* Beauty of a finish from {player}! 🌟'],
    miss: ['😩 {player} chips it a touch too long — wide!', '🧤 Keeper catches the lob! Good stop.'],
  },
  {
    build: ['🦶 {player} controls a bouncing ball...', 'Instantly brings it down...'],
    options: [
      { key: 'a', label: 'First-Time Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Half-Volley', gw: 1.1, aliases: ['volley'] },
      { key: 'c', label: 'Settles & Shoots', gw: 1.0, aliases: ['shoot'] },
      { key: 'd', label: 'Cushion Pass', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *VOLLEY GOAL!* {player} catches it sweet! 💥', '🌟 *GOAL!* First-time finish, no mercy! {team} go mad! 🔥'],
    miss: ['😬 {player} slices the volley — miles off!', '🧤 Keeper gets down to it!'],
  },
  {
    build: ['🤸 {player} goes for the spectacular...', 'Back to goal, audacious...'],
    options: [
      { key: 'a', label: 'Bicycle Kick', gw: 1.2, aliases: ['bicycle', 'scissor'] },
      { key: 'b', label: 'Scissor Kick', gw: 1.15, aliases: ['scissor'] },
      { key: 'c', label: 'Turn & Shoot', gw: 1.05, aliases: ['turn', 'shot'] },
      { key: 'd', label: 'Flick Header', gw: 1.0, aliases: ['flick', 'header'] },
    ],
    goal: ['⚽ *BIKE! GOAL!!* {player} is UNREAL! 🤩', '🌟 *GOAL!* That\'s outrageous skill from {player}! 🔥'],
    miss: ['😱 {player} mistimes the acrobatics — no contact!', '🧤 Keeper claims the awkward effort.'],
  },
  {
    build: ['🥅 {player} is six yards out...', 'Tap-in territory...'],
    options: [
      { key: 'a', label: 'Tap In', gw: 1.25, aliases: ['tap', 'finish'] },
      { key: 'b', label: 'Poacher', gw: 1.2, aliases: ['poach'] },
      { key: 'c', label: 'Sidefoot', gw: 1.15, aliases: ['sidefoot'] },
      { key: 'd', label: 'Backheel Flick', gw: 1.0, aliases: ['backheel'] },
    ],
    goal: ['⚽ *TAP-IN! GOAL!* {player} can\'t miss! 😅', '💥 *GOAL!* Poacher\'s finish from {player}! 🔥'],
    miss: ['😩 {player} somehow misses an open goal! 😂', '🧱 Blocked on the line! {opp} defend bravely!'],
  },
  {
    build: ['🔁 Loose ball in the box!', '{player} is first to the rebound!'],
    options: [
      { key: 'a', label: 'Smash Rebound', gw: 1.2, aliases: ['smash', 'shot'] },
      { key: 'b', label: 'Sidefoot', gw: 1.1, aliases: ['sidefoot'] },
      { key: 'c', label: 'Lob Rebound', gw: 1.0, aliases: ['lob'] },
      { key: 'd', label: 'Square It', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} pounces on the rebound! 💥', '🔥 *GOAL!* {team} profit from the scramble! 🤩'],
    miss: ['😤 {player} blazes the rebound over!', '🧤 Keeper grabs the loose ball!'],
  },
  {
    build: ['🏃 {player} goes on a mazy solo run...', 'Beats one... beats two...'],
    options: [
      { key: 'a', label: 'Solo Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Roulette', gw: 1.05, aliases: ['roulette'] },
      { key: 'c', label: 'One-Two', gw: 1.0, aliases: ['onetwo', 'pass'] },
      { key: 'd', label: 'Trivela', gw: 1.1, aliases: ['trivela', 'curl'] },
    ],
    goal: ['⚽ *GOAL!* {player} dances through and scores! 💃', '🌟 *GOAL!!* Solo magic from {player}! 🔥'],
    miss: ['🔄 {player} runs into a dead end — tackled!', '😱 {player} shoots from a tight angle — wide!'],
  },
  {
    build: ['🪽 {team} swing a crossfield ball...', '{player} races onto it on the wing...'],
    options: [
      { key: 'a', label: 'Winger Cut In', gw: 1.15, aliases: ['cut', 'shot'] },
      { key: 'b', label: 'Low Cross', gw: 1.0, aliases: ['cross'] },
      { key: 'c', label: 'Hug Line', gw: 0.95, aliases: ['hug'] },
      { key: 'd', label: 'Stepover', gw: 1.05, aliases: ['stepover'] },
    ],
    goal: ['⚽ *GOAL!* {player} cuts inside and curls it in! 😍', '💥 *GOAL!* Brilliant winger\'s finish! 🔥'],
    miss: ['😬 {player} overcooks the cross — out for a throw.', '🧤 Keeper gathers the delivery.'],
  },
  {
    build: ['🎯 Deflected shot!', 'The ball falls kindly to {player}...'],
    options: [
      { key: 'a', label: 'Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Half-Volley', gw: 1.1, aliases: ['volley'] },
      { key: 'c', label: 'Flick', gw: 1.0, aliases: ['flick'] },
      { key: 'd', label: 'Square', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} reacts quickest! 💥', '🔥 *GOAL!* A bit of luck for {team}! 🍀'],
    miss: ['😩 {player} can\'t sort his feet out — cleared!', '🧤 Keeper smothers the loose ball.'],
  },
  {
    build: ['🤡 {player} steps up for the Panenka...', 'Keeper guessing...'],
    options: [
      { key: 'a', label: 'Panenka', gw: 1.25, aliases: ['panenka', 'chip'] },
      { key: 'b', label: 'Send Keeper', gw: 1.15, aliases: ['corner'] },
      { key: 'c', label: 'Stutter Shot', gw: 1.1, aliases: ['shot'] },
      { key: 'd', label: 'Roll', gw: 1.0, aliases: ['roll'] },
    ],
    goal: ['⚽ *PANENKA GOAL!* {player} rolls it down the middle! 😏', '💥 *GOAL!* Pure cheek from {player}! 🔥'],
    miss: ['😱 Keeper doesn\'t bite — saves the Panenka! 🧤', '😩 {player} panics and skies it!'],
  },
  {
    build: ['🦵 {player} shapes for a Rabona...', 'Fancy stuff on the left flank...'],
    options: [
      { key: 'a', label: 'Rabona Shot', gw: 1.15, aliases: ['rabona', 'shot'] },
      { key: 'b', label: 'Rabona Cross', gw: 1.0, aliases: ['cross'] },
      { key: 'c', label: 'Switch', gw: 0.95, aliases: ['switch'] },
      { key: 'd', label: 'Cut In', gw: 1.05, aliases: ['cut'] },
    ],
    goal: ['⚽ *RABONA GOAL!* {player} is a wizard! 🪄', '🌟 *GOAL!* Unbelievable technique! 🔥'],
    miss: ['😬 {player} shanks the rabona — out of play.', '🧤 Keeper catches the cross.'],
  },
  {
    build: ['🌀 {player} winds up a Trivela...', 'Curling one from the right...'],
    options: [
      { key: 'a', label: 'Trivela', gw: 1.2, aliases: ['trivela', 'curl', 'shot'] },
      { key: 'b', label: 'Drive', gw: 1.1, aliases: ['drive'] },
      { key: 'c', label: 'Cutback', gw: 1.0, aliases: ['cutback', 'pass'] },
      { key: 'd', label: 'Fake', gw: 0.95, aliases: ['fake'] },
    ],
    goal: ['⚽ *TRIVELA GOAL!* {player} bends it into the top corner! 😍', '💥 *GOAL!* Filth from the winger! 🔥'],
    miss: ['😩 {player} drags the trivela wide!', '🧤 Keeper tips it round the post!'],
  },
  {
    build: ['👟 {player} tries the outside-of-the-boot...', 'Trying to catch the keeper off guard...'],
    options: [
      { key: 'a', label: 'Curl', gw: 1.15, aliases: ['curl', 'shot'] },
      { key: 'b', label: 'Sidefoot', gw: 1.1, aliases: ['sidefoot'] },
      { key: 'c', label: 'Chip', gw: 1.05, aliases: ['chip'] },
      { key: 'd', label: 'Pass', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} caresses it in with the outside! 🪄', '💥 *GOAL!* Classy finish! 🔥'],
    miss: ['😬 {player} mishits it — easy for the keeper.', '🧱 Blocked!'],
  },
  {
    build: ['⚡ Close range for {player}...', 'The keeper is right there...'],
    options: [
      { key: 'a', label: 'Near Post', gw: 1.2, aliases: ['near', 'shot'] },
      { key: 'b', label: 'Far Corner', gw: 1.15, aliases: ['far', 'corner'] },
      { key: 'c', label: 'Chip Keeper', gw: 1.1, aliases: ['chip'] },
      { key: 'd', label: 'Pull Back', gw: 0.95, aliases: ['pull', 'pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} slots it past the keeper! 💥', '🔥 *GOAL!* Clinical from close range! 🔥'],
    miss: ['😱 {player} hits the keeper\'s legs!', '🧤 Brilliant stop from close range!'],
  },
  {
    build: ['🧱 Free kick over the wall...', '{player} sizes it up...'],
    options: [
      { key: 'a', label: 'Over Wall', gw: 1.15, aliases: ['over'] },
      { key: 'b', label: 'Under Wall', gw: 1.05, aliases: ['under'] },
      { key: 'c', label: 'Knuckleball', gw: 1.1, aliases: ['knuckle'] },
      { key: 'd', label: 'Pass', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *FREE KICK GOAL!* {player} lifts it over the wall! 😍', '💥 *GOAL!* Dip and nonsense from {player}! 🔥'],
    miss: ['🧱 Wall blocks it! {opp} clear.', '😩 {player} sends it over!'],
  },
  {
    build: ['⚡ Quick free kick taken!', '{player} spins away from the marker...'],
    options: [
      { key: 'a', label: 'Quick Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Dribble', gw: 1.05, aliases: ['dribble', 'run'] },
      { key: 'c', label: 'Release', gw: 1.0, aliases: ['pass'] },
      { key: 'd', label: 'Hold Up', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} takes it quick and scores! 💨', '🔥 *GOAL!* Caught {opp} napping! ⚡'],
    miss: ['🔄 {player} flagged for the quick free kick — no advantage.', '🧤 Keeper saves the effort.'],
  },
  {
    build: ['🤾 Throw-in deep in {opp} half...', '{player} launches a long one...'],
    options: [
      { key: 'a', label: 'Long Throw', gw: 1.1, aliases: ['long'] },
      { key: 'b', label: 'Short', gw: 0.95, aliases: ['short'] },
      { key: 'c', label: 'Flick On', gw: 1.0, aliases: ['flick'] },
      { key: 'd', label: 'Quick Break', gw: 1.05, aliases: ['break'] },
    ],
    goal: ['⚽ *GOAL FROM THE THROW!* {player} attacks it! 💥', '🔥 *GOAL!* Long throw causes chaos! 😤'],
    miss: ['🧱 Cleared from the resulting corner.', '😬 {player} can\'t control the long throw.'],
  },
  {
    build: ['🚀 {team} go direct...', 'Long ball over the top finds {player}...'],
    options: [
      { key: 'a', label: 'Control & Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Volley', gw: 1.1, aliases: ['volley'] },
      { key: 'c', label: 'Knock Down', gw: 1.0, aliases: ['knock', 'pass'] },
      { key: 'd', label: 'Hold Up', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} brings it down and buries it! 💥', '🌟 *GOAL!* Perfect long-ball finish! 🔥'],
    miss: ['😱 {player} can\'t control the long ball — gone.', '🚩 Offside flag up!'],
  },
  {
    build: ['🔁 {team} play tiki-taka...', 'One-two, one-two... {player} finds a pocket...'],
    options: [
      { key: 'a', label: 'One-Two Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Wall Pass', gw: 1.05, aliases: ['wall', 'pass'] },
      { key: 'c', label: 'Thread', gw: 1.1, aliases: ['thread', 'through'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} finishes the move! 🎯', '🔥 *GOAL!* Beautiful team goal! 🤩'],
    miss: ['🔄 {player} overplays it — intercepted!', '🧤 Keeper claims the final ball.'],
  },
  {
    build: ['💃 {player} shows the stepover...', 'Defender bites...'],
    options: [
      { key: 'a', label: 'Stepover Shot', gw: 1.15, aliases: ['stepover', 'shot'] },
      { key: 'b', label: 'Body Feint', gw: 1.05, aliases: ['feint'] },
      { key: 'c', label: 'Explode Past', gw: 1.1, aliases: ['explode', 'run'] },
      { key: 'd', label: 'Backheel', gw: 0.95, aliases: ['backheel'] },
    ],
    goal: ['⚽ *GOAL!* {player} leaves him for dead and scores! 😤', '💥 *GOAL!* Defender absolutely cooked! 🔥'],
    miss: ['🔄 {player} loses balance after the stepover!', '🧱 Tackled as he tries to go past.'],
  },
  {
    build: ['🔄 Cruyff turn from {player}...', 'Creates a yard of space...'],
    options: [
      { key: 'a', label: 'Turn & Shoot', gw: 1.15, aliases: ['shot', 'turn'] },
      { key: 'b', label: 'Cruyff Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Drive', gw: 1.1, aliases: ['drive'] },
      { key: 'd', label: 'Drop Shoulder', gw: 1.05, aliases: ['shoulder'] },
    ],
    goal: ['⚽ *GOAL!* {player} turns and fires home! 💥', '🔥 *GOAL!* Classic Cruyff finish! 🔥'],
    miss: ['😬 {player} drags the turn-shot wide.', '🧤 Keeper saves the effort.'],
  },
  {
    build: ['🪩 {player} hits the elastico...', 'Body goes one way, ball the other...'],
    options: [
      { key: 'a', label: 'Elastico Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Elastico Run', gw: 1.1, aliases: ['run'] },
      { key: 'c', label: 'Double Touch', gw: 1.0, aliases: ['double'] },
      { key: 'd', label: 'Pass', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} breaks the ankles and scores! 😂', '🌟 *GOAL!* Elastico magic! 🔥'],
    miss: ['🔄 {player} loses it after the flick — cleared!', '🧱 Blocked!'],
  },
  {
    build: ['🌈 {player} attempts a rainbow flick...', 'Trying to go over the defender...'],
    options: [
      { key: 'a', label: 'Rainbow Finish', gw: 1.1, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Rainbow Run', gw: 1.05, aliases: ['run'] },
      { key: 'c', label: 'Volley', gw: 1.1, aliases: ['volley'] },
      { key: 'd', label: 'Recover', gw: 0.9, aliases: ['recover'] },
    ],
    goal: ['⚽ *GOAL!* {player} flips it over and finishes! 🌈', '🌟 *GOAL!* Outrageous rainbow! 🔥'],
    miss: ['😬 {player} mistimes the flick — defender clears.', '🧱 The rainbow balloons out of play.'],
  },
  {
    build: ['🔙 {player} backheels it...', 'Trying something special...'],
    options: [
      { key: 'a', label: 'Backheel Finish', gw: 1.1, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Backheel Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Spin & Shoot', gw: 1.05, aliases: ['spin', 'shot'] },
      { key: 'd', label: 'Flick', gw: 0.95, aliases: ['flick'] },
    ],
    goal: ['⚽ *GOAL!* {player} backheels it in! 😱', '🌟 *GOAL!* No-look finish! 🔥'],
    miss: ['🔄 {player} backheels it straight to a defender.', '🧤 Keeper gathers.'],
  },
  {
    build: ['⚡ {player} meets it first time...', 'No second touch...'],
    options: [
      { key: 'a', label: 'First-Time Shot', gw: 1.2, aliases: ['shot', 'finish'] },
      { key: 'b', label: 'First-Time Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Side Volley', gw: 1.15, aliases: ['volley'] },
      { key: 'd', label: 'Cushion', gw: 0.9, aliases: ['cushion'] },
    ],
    goal: ['⚽ *GOAL!* {player} catches it flush first time! 💥', '🔥 *GOAL!* Instinctive finish! 🤩'],
    miss: ['😬 {player} screws the first-time effort wide.', '🧱 Blocked by a defender\'s body.'],
  },
  {
    build: ['⏱️ Half-volley chance for {player}...', 'Ball dropping nicely...'],
    options: [
      { key: 'a', label: 'Half-Volley', gw: 1.2, aliases: ['volley'] },
      { key: 'b', label: 'Place', gw: 1.1, aliases: ['place', 'shot'] },
      { key: 'c', label: 'Sidefoot', gw: 1.05, aliases: ['sidefoot'] },
      { key: 'd', label: 'Lay Off', gw: 0.9, aliases: ['lay', 'pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} half-volleys it into the roof! 💥', '🌟 *GOAL!* Textbook strike! 🔥'],
    miss: ['😩 {player} shanks the half-volley — high and wide!', '🧤 Keeper holds it.'],
  },
  {
    build: ['✂️ Scissor-kick opportunity!', '{player} leaps for the bicycle...'],
    options: [
      { key: 'a', label: 'Scissor Kick', gw: 1.2, aliases: ['scissor', 'bicycle'] },
      { key: 'b', label: 'Overhead', gw: 1.15, aliases: ['overhead'] },
      { key: 'c', label: 'Header', gw: 1.1, aliases: ['header'] },
      { key: 'd', label: 'Volley', gw: 1.1, aliases: ['volley'] },
    ],
    goal: ['⚽ *SCISSOR GOAL!* {player} is airborne brilliance! 🤩', '🌟 *GOAL!* What an athletic finish! 🔥'],
    miss: ['😱 {player} overrotates — misses everything!', '🧤 Keeper claims the looping effort.'],
  },
  {
    build: ['🆙 {player} looks to lob the keeper...', 'Keeper stranded...'],
    options: [
      { key: 'a', label: 'Lob', gw: 1.2, aliases: ['lob', 'chip'] },
      { key: 'b', label: 'Place', gw: 1.1, aliases: ['place'] },
      { key: 'c', label: 'Dink', gw: 1.1, aliases: ['dink'] },
      { key: 'd', label: 'Roll', gw: 0.95, aliases: ['roll'] },
    ],
    goal: ['⚽ *LOB GOAL!* {player} dinks it over the stranded keeper! 😍', '💥 *GOAL!* Lovely weight of pass! 🔥'],
    miss: ['😩 {player} lobs it a yard too long — wide!', '🧤 Keeper backpedals and catches it!'],
  },
  {
    build: ['💥 {player} hits a driven shot...', 'Keeping it low and hard...'],
    options: [
      { key: 'a', label: 'Driven', gw: 1.2, aliases: ['drive', 'shot'] },
      { key: 'b', label: 'Low Corner', gw: 1.15, aliases: ['corner'] },
      { key: 'c', label: 'Strike', gw: 1.1, aliases: ['strike'] },
      { key: 'd', label: 'Pass', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} stings it past the keeper! 💥', '🔥 *GOAL!* Unstoppable driven finish! 🔥'],
    miss: ['🧱 Blocked by a last-ditch body!', '😬 {player} drags it just wide.'],
  },
  {
    build: ['🌀 {player} curls one from the edge...', 'Looking for the top corner...'],
    options: [
      { key: 'a', label: 'Curl', gw: 1.2, aliases: ['curl', 'shot'] },
      { key: 'b', label: 'Inswing', gw: 1.1, aliases: ['inswing'] },
      { key: 'c', label: 'Dip', gw: 1.1, aliases: ['dip'] },
      { key: 'd', label: 'Pass', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *CURLER GOAL!* {player} bends it round the keeper! 😍', '💥 *GOAL!* Exquisite curl! 🔥'],
    miss: ['😩 {player} curls it onto the roof of the net!', '🧤 Keeper pushes it round!'],
  },
  {
    build: ['💪 {player} rises for a power header...', 'Beating the defender in the air...'],
    options: [
      { key: 'a', label: 'Power Header', gw: 1.2, aliases: ['header'] },
      { key: 'b', label: 'Glance', gw: 1.1, aliases: ['glance'] },
      { key: 'c', label: 'Downward', gw: 1.15, aliases: ['down'] },
      { key: 'd', label: 'Flick', gw: 0.95, aliases: ['flick'] },
    ],
    goal: ['⚽ *POWER HEADER GOAL!* {player} nods it in! 💪', '💥 *GOAL!* Strong as an ox! 🔥'],
    miss: ['😬 {player} heads it straight at the keeper.', '🚫 Cleared off the line!'],
  },
  {
    build: ['🐀 {player} is the poacher in the box...', 'Sniffing a chance...'],
    options: [
      { key: 'a', label: 'Poach', gw: 1.25, aliases: ['poach', 'finish'] },
      { key: 'b', label: 'Tap', gw: 1.2, aliases: ['tap'] },
      { key: 'c', label: 'Toe Poke', gw: 1.15, aliases: ['poke'] },
      { key: 'd', label: 'Square', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} is in the right place! 🐀', '💥 *GOAL!* Poacher\'s instinct! 🔥'],
    miss: ['😩 {player} just can\'t connect — cleared!', '🧤 Keeper smothers.'],
  },
  {
    build: ['🌪️ {player} goes on a mazy dribble...', 'Weaving through bodies...'],
    options: [
      { key: 'a', label: 'Dribble Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Double Tap', gw: 1.05, aliases: ['double'] },
      { key: 'c', label: 'Shoulder Drop', gw: 1.1, aliases: ['shoulder'] },
      { key: 'd', label: 'Backheel', gw: 0.95, aliases: ['backheel'] },
    ],
    goal: ['⚽ *GOAL!* {player} weaves through and scores! 🌪️', '🌟 *GOAL!* Mesmerising run! 🔥'],
    miss: ['🔄 {player} runs into traffic — dispossessed!', '🧱 Tackled from behind — foul!'],
  },
  {
    build: ['🔁 {player} plays a one-two...', 'Trying to unlock the defence...'],
    options: [
      { key: 'a', label: 'One-Two Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Wall Pass', gw: 1.05, aliases: ['wall', 'pass'] },
      { key: 'c', label: 'Give & Go', gw: 1.1, aliases: ['go'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} releases and finishes the one-two! 🎯', '🔥 *GOAL!* Slick combination! 🤩'],
    miss: ['🔄 The return pass is cut out!', '🧤 Keeper intercepts the through ball.'],
  },
  {
    build: ['🔀 {team} switch the play...', '{player} receives on the opposite flank...'],
    options: [
      { key: 'a', label: 'Switch Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Diagonal', gw: 1.05, aliases: ['diagonal', 'pass'] },
      { key: 'c', label: 'Cut In', gw: 1.1, aliases: ['cut'] },
      { key: 'd', label: 'Overlap', gw: 1.0, aliases: ['overlap'] },
    ],
    goal: ['⚽ *GOAL!* {player} switches it and scores! 🔀', '💥 *GOAL!* Great switch of play! 🔥'],
    miss: ['😬 {player} overhits the diagonal — out of play.', '🧤 Keeper claims.'],
  },
  {
    build: ['⬆️ Overlapping run from {player}...', 'Arriving late in the box...'],
    options: [
      { key: 'a', label: 'Overlap Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Cutback', gw: 1.0, aliases: ['cutback', 'pass'] },
      { key: 'c', label: 'Low Cross', gw: 1.0, aliases: ['cross'] },
      { key: 'd', label: 'Pull Back', gw: 0.95, aliases: ['pull'] },
    ],
    goal: ['⚽ *GOAL!* {player} arrives late and scores! ⬆️', '💥 *GOAL!* Perfect overlap! 🔥'],
    miss: ['😩 {player} can\'t get the shot away — blocked!', '🧤 Keeper saves.'],
  },
  {
    build: ['✂️ {player} cuts it back from the byline...', 'Pulling it back into danger...'],
    options: [
      { key: 'a', label: 'Cutback Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Pull Back', gw: 1.0, aliases: ['pull', 'pass'] },
      { key: 'c', label: 'Low Driven', gw: 1.1, aliases: ['driven'] },
      { key: 'd', label: 'Square', gw: 0.95, aliases: ['square'] },
    ],
    goal: ['⚽ *GOAL!* {player} cuts it back and scores! ✂️', '💥 *GOAL!* Deadly cutback! 🔥'],
    miss: ['🔄 The cutback is intercepted!', '🧤 Keeper claims the pulled-back ball.'],
  },
  {
    build: ['🔻 Low cross into the box...', '{player} gambles at the near post...'],
    options: [
      { key: 'a', label: 'Near Post', gw: 1.2, aliases: ['near', 'finish'] },
      { key: 'b', label: 'Flick', gw: 1.0, aliases: ['flick'] },
      { key: 'c', label: 'Sidefoot', gw: 1.1, aliases: ['sidefoot'] },
      { key: 'd', label: 'Deflect', gw: 0.95, aliases: ['deflect'] },
    ],
    goal: ['⚽ *GOAL!* {player} steers the low cross in! 🔻', '💥 *GOAL!* Great near-post finish! 🔥'],
    miss: ['🧱 Defender gets a toe to it — cleared!', '😬 {player} can\'t connect cleanly.'],
  },
  {
    build: ['🔝 Flick-on at the near post...', '{player} flicks it on...'],
    options: [
      { key: 'a', label: 'Flick Goal', gw: 1.15, aliases: ['flick', 'finish'] },
      { key: 'b', label: 'Flick Across', gw: 1.0, aliases: ['across', 'pass'] },
      { key: 'c', label: 'Glance', gw: 1.05, aliases: ['glance'] },
      { key: 'd', label: 'Header', gw: 1.1, aliases: ['header'] },
    ],
    goal: ['⚽ *GOAL!* {player} flicks it into the net! 🔝', '💥 *GOAL!* Clever flick! 🔥'],
    miss: ['😬 {player} flicks it just wide.', '🧤 Keeper grabs the flick-on.'],
  },
  {
    build: ['📺 VAR check! Was it a foul?', 'Ref points to the spot — penalty for {team}!', '{player} steps up...'],
    options: [
      { key: 'a', label: 'Confident', gw: 1.2, aliases: ['corner', 'power'] },
      { key: 'b', label: 'Stutter', gw: 1.1, aliases: ['stutter', 'shot'] },
      { key: 'c', label: 'Panenka', gw: 1.25, aliases: ['panenka', 'chip'] },
      { key: 'd', label: 'Wait', gw: 0.9, aliases: ['wait'] },
    ],
    goal: ['⚽ *VAR CONFIRMS — GOAL!* {player} scores! 📺', '💥 *GOAL!* The ref got it right! 🔥'],
    miss: ['🧤 VAR can\'t help — keeper saves!', '😩 {player} blazes the VAR penalty over!'],
  },
  {
    build: ['⏰ Last minute of the match!', '{player} has a golden chance to win it...'],
    options: [
      { key: 'a', label: 'Winner', gw: 1.2, aliases: ['shot', 'finish'] },
      { key: 'b', label: 'Composed', gw: 1.15, aliases: ['place'] },
      { key: 'c', label: 'Chip', gw: 1.1, aliases: ['chip'] },
      { key: 'd', label: 'Lay Off', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *90TH MINUTE WINNER!* {player} delivers! 😱', '🌟 *GOAL!* {team} snatch it at the death! 🔥'],
    miss: ['😩 {player} misses the last-gasp chance!', '🧤 Keeper denies at the death!'],
  },
  {
    build: ['🏃 {player} is chased down...', 'Defender closing fast...'],
    options: [
      { key: 'a', label: 'Finish Under Press', gw: 1.15, aliases: ['shot', 'finish'] },
      { key: 'b', label: 'Shield & Shoot', gw: 1.05, aliases: ['shield'] },
      { key: 'c', label: 'Pass Away', gw: 1.0, aliases: ['pass'] },
      { key: 'd', label: 'Spin Away', gw: 1.05, aliases: ['spin'] },
    ],
    goal: ['⚽ *GOAL!* {player} scores with a defender on his back! 💪', '💥 *GOAL!* Composed under pressure! 🔥'],
    miss: ['🔄 Chased down and tackled!', '🧤 Keeper saves the rushed effort.'],
  },
  {
    build: ['🧤 Keeper rushes off his line!', '{player} must decide quickly...'],
    options: [
      { key: 'a', label: 'Chip Keeper', gw: 1.2, aliases: ['chip'] },
      { key: 'b', label: 'Round', gw: 1.15, aliases: ['round'] },
      { key: 'c', label: 'Toe Poke', gw: 1.1, aliases: ['poke'] },
      { key: 'd', label: 'Pass', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} dinks it over the rushing keeper! 😍', '💥 *GOAL!* Perfect read! 🔥'],
    miss: ['😱 Keeper smothers the chip!', '🔄 {player} clatters into the keeper — foul!'],
  },
  {
    build: ['🧱 Wall set for the free kick...', '{player} eyes the gap...'],
    options: [
      { key: 'a', label: 'Through Wall', gw: 1.15, aliases: ['through'] },
      { key: 'b', label: 'Over Wall', gw: 1.1, aliases: ['over'] },
      { key: 'c', label: 'Under Wall', gw: 1.05, aliases: ['under'] },
      { key: 'd', label: 'Dummy', gw: 0.95, aliases: ['dummy'] },
    ],
    goal: ['⚽ *GOAL!* {player} threads it through the wall! 🧱', '💥 *GOAL!* Free-kick special! 🔥'],
    miss: ['🧱 Wall blocks again!', '😩 {player} hits it straight into the wall.'],
  },
  {
    build: ['🚩 Short corner taken...', '{player} plays it back to the taker...'],
    options: [
      { key: 'a', label: 'Shot From Angle', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Cross Again', gw: 1.0, aliases: ['cross'] },
      { key: 'c', label: 'Cut In', gw: 1.1, aliases: ['cut'] },
      { key: 'd', label: 'One-Two', gw: 1.05, aliases: ['onetwo', 'pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} scores from the short corner! 🚩', '💥 *GOAL!* Cute routine! 🔥'],
    miss: ['🔄 {opp} read the short corner — cleared!', '🧤 Keeper saves the angle effort.'],
  },
  {
    build: ['🚩 Deep corner swung in...', '{player} attacks the back post...'],
    options: [
      { key: 'a', label: 'Back-Post Header', gw: 1.2, aliases: ['header'] },
      { key: 'b', label: 'Volley', gw: 1.15, aliases: ['volley'] },
      { key: 'c', label: 'Flick', gw: 1.0, aliases: ['flick'] },
      { key: 'd', label: 'Control', gw: 0.9, aliases: ['control'] },
    ],
    goal: ['⚽ *GOAL!* {player} powers in at the back post! 🚩', '💥 *GOAL!* Great delivery and finish! 🔥'],
    miss: ['😬 {player} can\'t reach the deep corner.', '🧤 Keeper punches it clear.'],
  },
  {
    build: ['⚡ {team} break with numbers!', '{player} has runners either side...'],
    options: [
      { key: 'a', label: 'Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Square', gw: 1.0, aliases: ['square', 'pass'] },
      { key: 'c', label: 'Cut Back', gw: 1.05, aliases: ['cutback'] },
      { key: 'd', label: 'Dribble', gw: 1.1, aliases: ['dribble', 'run'] },
    ],
    goal: ['⚽ *GOAL!* {player} finishes the break! ⚡', '💥 *GOAL!* {team} ruthless on the counter! 🔥'],
    miss: ['🔄 The final ball is overhit — gone.', '🧤 Keeper rushes out and blocks.'],
  },
  {
    build: ['🔝 {team} press high...', 'Win it back and {player} is through...'],
    options: [
      { key: 'a', label: 'Press Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Drive', gw: 1.1, aliases: ['drive'] },
      { key: 'c', label: 'Slide', gw: 1.05, aliases: ['slide', 'pass'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} punishes the high press! 🔝', '💥 *GOAL!* Turnover and finish! 🔥'],
    miss: ['🔄 {player} caught offside from the press.', '🧤 Keeper saves.'],
  },
  {
    build: ['🚀 {team} launch a long throw...', 'Into the mixer, {player} attacks it...'],
    options: [
      { key: 'a', label: 'Throw Header', gw: 1.2, aliases: ['header'] },
      { key: 'b', label: 'Flick', gw: 1.0, aliases: ['flick'] },
      { key: 'c', label: 'Volley', gw: 1.15, aliases: ['volley'] },
      { key: 'd', label: 'Knock Down', gw: 1.0, aliases: ['knock', 'pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} meets the long throw! 🚀', '💥 *GOAL!* Set-piece chaos pays off! 🔥'],
    miss: ['🧱 Cleared from the scramble.', '😬 {player} can\'t get a clean header.'],
  },
  {
    build: ['🌀 {player} rolls the defender with a roulette...', 'Space opens up...'],
    options: [
      { key: 'a', label: 'Roulette Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Roulette Run', gw: 1.1, aliases: ['run'] },
      { key: 'c', label: 'Spin Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'd', label: 'Drop Shoulder', gw: 1.05, aliases: ['shoulder'] },
    ],
    goal: ['⚽ *GOAL!* {player} spins and scores! 🌀', '💥 *GOAL!* Silky roulette finish! 🔥'],
    miss: ['🔄 {player} loses it after the spin.', '🧱 Tackled.'],
  },
  {
    build: ['🦅 {player} rises above everyone...', 'Aerial duel won...'],
    options: [
      { key: 'a', label: 'Aerial Header', gw: 1.2, aliases: ['header'] },
      { key: 'b', label: 'Flick On', gw: 1.0, aliases: ['flick'] },
      { key: 'c', label: 'Downward', gw: 1.15, aliases: ['down'] },
      { key: 'd', label: 'Volley', gw: 1.1, aliases: ['volley'] },
    ],
    goal: ['⚽ *GOAL!* {player} wins the header and scores! 🦅', '💥 *GOAL!* Dominant in the air! 🔥'],
    miss: ['😬 {player} heads wide under pressure.', '🧤 Keeper claims the high ball.'],
  },
  {
    build: ['🎯 {player} lines up a first-time sidefoot...', 'Cushioned pass into his path...'],
    options: [
      { key: 'a', label: 'Sidefoot', gw: 1.2, aliases: ['sidefoot', 'finish'] },
      { key: 'b', label: 'Half-Volley', gw: 1.15, aliases: ['volley'] },
      { key: 'c', label: 'Place', gw: 1.1, aliases: ['place'] },
      { key: 'd', label: 'Square', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} sidefoots it home first time! 🎯', '💥 *GOAL!* Cool finish! 🔥'],
    miss: ['😩 {player} sidefoots it wide!', '🧤 Keeper saves the sidefoot.'],
  },
  {
    build: ['🔀 {player} plays a reverse pass...', 'Trying to slip it through...'],
    options: [
      { key: 'a', label: 'Reverse Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Reverse Pass', gw: 1.05, aliases: ['pass'] },
      { key: 'c', label: 'Turn', gw: 1.1, aliases: ['turn'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} plays the reverse and scores! 🔀', '💥 *GOAL!* Clever reverse! 🔥'],
    miss: ['🔄 The reverse pass is read — intercepted!', '🧤 Keeper saves.'],
  },
  {
    build: ['💨 {player} uses raw pace to blow past...', 'Sprints in behind...'],
    options: [
      { key: 'a', label: 'Pace Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Toe Poke', gw: 1.1, aliases: ['poke'] },
      { key: 'c', label: 'Chip', gw: 1.1, aliases: ['chip'] },
      { key: 'd', label: 'Square', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} uses his pace to score! 💨', '💥 *GOAL!* Blistering finish! 🔥'],
    miss: ['🚩 {player} is flagged offside after the sprint.', '🧤 Keeper out quickly to smother.'],
  },
  {
    build: ['🪄 {player} tries a no-look pass then shoots...', 'Blind finish attempt...'],
    options: [
      { key: 'a', label: 'No-Look Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'No-Look Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Spin', gw: 1.05, aliases: ['spin'] },
      { key: 'd', label: 'Dummy', gw: 0.95, aliases: ['dummy'] },
    ],
    goal: ['⚽ *GOAL!* {player} scores without looking! 🪄', '🌟 *GOAL!* Pure swagger! 🔥'],
    miss: ['😬 {player} doesn\'t connect — no-look miscue!', '🧤 Keeper saves the blind effort.'],
  },
  {
    build: ['🧨 {player} lines up a thunderbastard from distance...', 'Everybody back!'],
    options: [
      { key: 'a', label: 'Thunderbastard', gw: 1.2, aliases: ['shot', 'bolt'] },
      { key: 'b', label: 'Low Drive', gw: 1.1, aliases: ['drive'] },
      { key: 'c', label: 'Knuckle', gw: 1.15, aliases: ['knuckle'] },
      { key: 'd', label: 'Pass', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *THUNDERBASTARD GOAL!* {player} nearly bursts the net! 🧨', '💥 *GOAL!* What a hit! 🔥'],
    miss: ['🧱 Blocked by a brave defender!', '😩 {player} catches it sweet but wide!'],
  },
  {
    build: ['🥅 {player} one-on-one, keeper narrowing the angle...', 'Big decision...'],
    options: [
      { key: 'a', label: 'Near Post', gw: 1.2, aliases: ['near', 'shot'] },
      { key: 'b', label: 'Far Corner', gw: 1.15, aliases: ['far', 'corner'] },
      { key: 'c', label: 'Chip', gw: 1.1, aliases: ['chip'] },
      { key: 'd', label: 'Panenka', gw: 1.25, aliases: ['panenka'] },
    ],
    goal: ['⚽ *GOAL!* {player} beats the keeper one-on-one! 🥅', '💥 *GOAL!* Composed in the duel! 🔥'],
    miss: ['🧤 Keeper saves the one-on-one!', '😱 {player} puts it wide with the goal at his mercy!'],
  },
  {
    build: ['🌀 {player} rolls a Cruyff turn then shoots...', 'Creating space on the edge...'],
    options: [
      { key: 'a', label: 'Cruyff Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Cruyff Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Drive', gw: 1.1, aliases: ['drive'] },
      { key: 'd', label: 'Drop', gw: 1.05, aliases: ['drop'] },
    ],
    goal: ['⚽ *GOAL!* {player} Cruyff-turns and scores! 🌀', '💥 *GOAL!* Sublime! 🔥'],
    miss: ['😬 {player} drags the effort wide.', '🧤 Keeper saves.'],
  },
  {
    build: ['🦶 {player} takes a first-touch cushioned volley...', 'Ball dropping perfectly...'],
    options: [
      { key: 'a', label: 'Cushion Volley', gw: 1.2, aliases: ['volley'] },
      { key: 'b', label: 'Place', gw: 1.1, aliases: ['place'] },
      { key: 'c', label: 'Sidefoot', gw: 1.05, aliases: ['sidefoot'] },
      { key: 'd', label: 'Lay Off', gw: 0.9, aliases: ['lay', 'pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} cushions it in first touch! 🦶', '💥 *GOAL!* Velvet finish! 🔥'],
    miss: ['😩 {player} mishits the volley — wide!', '🧤 Keeper holds.'],
  },
  {
    build: ['🌀 {player} drags the ball back with a sole roll...', 'Creating a shooting lane...'],
    options: [
      { key: 'a', label: 'Sole Roll Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Sole Roll Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Spin Away', gw: 1.05, aliases: ['spin'] },
      { key: 'd', label: 'Cut', gw: 1.1, aliases: ['cut'] },
    ],
    goal: ['⚽ *GOAL!* {player} drags and fires home! 🌀', '💥 *GOAL!* Smooth! 🔥'],
    miss: ['🔄 {player} loses it after the drag-back.', '🧤 Keeper saves.'],
  },
  {
    build: ['🦵 {player} takes a touch then unleashes...', 'Room opens up...'],
    options: [
      { key: 'a', label: 'Hit First Time', gw: 1.2, aliases: ['shot', 'finish'] },
      { key: 'b', label: 'Settle & Shoot', gw: 1.1, aliases: ['settle'] },
      { key: 'c', label: 'Driven', gw: 1.15, aliases: ['drive'] },
      { key: 'd', label: 'Pass', gw: 0.9, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} takes a touch and buries it! 🦵', '💥 *GOAL!* Ruthless! 🔥'],
    miss: ['😬 {player} takes a heavy touch — tackled!', '🧤 Keeper saves.'],
  },
  {
    build: ['🔥 Tension SKY HIGH!', '{player} has the ball in a packed box...'],
    options: [
      { key: 'a', label: 'Snap Shot', gw: 1.2, aliases: ['shot', 'finish'] },
      { key: 'b', label: 'Flick', gw: 1.0, aliases: ['flick'] },
      { key: 'c', label: 'Turn', gw: 1.1, aliases: ['turn'] },
      { key: 'd', label: 'Square', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} snaps it in amid the chaos! 🔥', '💥 *GOAL!* {team} erupt! 🤩'],
    miss: ['🔄 {player} crowded out — blocked!', '🧤 Keeper bravely smothers.'],
  },
  {
    build: ['🎯 {player} threads a pass then makes a run...', 'One-two around the defender...'],
    options: [
      { key: 'a', label: 'Run & Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Wall Pass', gw: 1.05, aliases: ['wall', 'pass'] },
      { key: 'c', label: 'Return Flick', gw: 1.1, aliases: ['flick'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} plays the one-two and finishes! 🎯', '💥 *GOAL!* Slick move! 🔥'],
    miss: ['🔄 The return is intercepted!', '🧤 Keeper saves the return.'],
  },
  {
    build: ['🆙 {player} beats the offside trap...', 'Through ball is perfect...'],
    options: [
      { key: 'a', label: 'Chip', gw: 1.2, aliases: ['chip'] },
      { key: 'b', label: 'Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'c', label: 'Round', gw: 1.1, aliases: ['round'] },
      { key: 'd', label: 'Square', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} stays onside and scores! 🆙', '💥 *GOAL!* Perfect timing! 🔥'],
    miss: ['🚩 {player} was a yard off — flag up!', '🧤 Keeper out to smother.'],
  },
  {
    build: ['🤸 {player} tries an audacious overhead...', 'Back to goal...'],
    options: [
      { key: 'a', label: 'Overhead', gw: 1.2, aliases: ['overhead', 'bicycle'] },
      { key: 'b', label: 'Volley', gw: 1.15, aliases: ['volley'] },
      { key: 'c', label: 'Turn', gw: 1.05, aliases: ['turn'] },
      { key: 'd', label: 'Flick', gw: 1.0, aliases: ['flick'] },
    ],
    goal: ['⚽ *OVERHEAD GOAL!* {player} is unreal! 🤸', '🌟 *GOAL!* Jaw-dropping! 🔥'],
    miss: ['😱 {player} mistimes the overhead — no contact!', '🧤 Keeper claims.'],
  },
  {
    build: ['🔥 Late chance for {player}...', 'Can he settle it?'],
    options: [
      { key: 'a', label: 'Composed', gw: 1.2, aliases: ['place', 'finish'] },
      { key: 'b', label: 'Power', gw: 1.15, aliases: ['shot'] },
      { key: 'c', label: 'Chip', gw: 1.1, aliases: ['chip'] },
      { key: 'd', label: 'Pass', gw: 0.95, aliases: ['pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} keeps his cool! 🔥', '💥 *GOAL!* Ice in the veins! 🧊'],
    miss: ['😩 {player} snatches at it — wide!', '🧤 Keeper saves the late chance.'],
  },
  {
    build: ['🌀 {player} nutmegs the last defender...', 'One-on-one with the keeper now...'],
    options: [
      { key: 'a', label: 'Nutmeg Finish', gw: 1.15, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Round Keeper', gw: 1.1, aliases: ['round'] },
      { key: 'c', label: 'Chip', gw: 1.1, aliases: ['chip'] },
      { key: 'd', label: 'Panenka', gw: 1.25, aliases: ['panenka'] },
    ],
    goal: ['⚽ *GOAL!* {player} nutmegs the last man and scores! 😂', '💥 *GOAL!* Humiliating for {opp}! 🔥'],
    miss: ['🔄 {player} overplays after the nutmeg — tackled!', '🧤 Keeper saves.'],
  },
  {
    build: ['🎯 {player} shoots with the outside of his weaker foot...', 'Trying to surprise the keeper...'],
    options: [
      { key: 'a', label: 'Weak-Foot Shot', gw: 1.15, aliases: ['shot'] },
      { key: 'b', label: 'Switch', gw: 1.0, aliases: ['switch', 'pass'] },
      { key: 'c', label: 'Cut In', gw: 1.1, aliases: ['cut'] },
      { key: 'd', label: 'Fake', gw: 0.95, aliases: ['fake'] },
    ],
    goal: ['⚽ *GOAL!* {player} scores with the wrong foot! 🎯', '💥 *GOAL!* Classy weak-foot finish! 🔥'],
    miss: ['😬 {player} mishits the weak-foot effort.', '🧤 Keeper saves.'],
  },
  {
    build: ['⚡ {player} picks up a loose ball on the break...', 'Two vs one...'],
    options: [
      { key: 'a', label: 'Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Square', gw: 1.0, aliases: ['square', 'pass'] },
      { key: 'c', label: 'Dribble', gw: 1.1, aliases: ['dribble', 'run'] },
      { key: 'd', label: 'Cut Back', gw: 1.05, aliases: ['cutback'] },
    ],
    goal: ['⚽ *GOAL!* {player} finishes the two-on-one! ⚡', '💥 *GOAL!* {team} punish the break! 🔥'],
    miss: ['🔄 The square pass is cut out!', '🧤 Keeper saves the breakaway.'],
  },
  {
    build: ['🧠 {player} reads the pass and intercepts...', 'Instant counter...'],
    options: [
      { key: 'a', label: 'Drive', gw: 1.15, aliases: ['drive', 'shot'] },
      { key: 'b', label: 'Surge', gw: 1.1, aliases: ['surge', 'run'] },
      { key: 'c', label: 'Through', gw: 1.05, aliases: ['through', 'pass'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} intercepts and scores! 🧠', '💥 *GOAL!* Brilliant read! 🔥'],
    miss: ['🔄 {player} caught in possession — tackled back!', '🧤 Keeper saves.'],
  },
  {
    build: ['🌀 {player} shows a fake shot then goes past...', 'Sending the keeper the wrong way...'],
    options: [
      { key: 'a', label: 'Fake & Finish', gw: 1.2, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Fake & Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Fake & Round', gw: 1.1, aliases: ['round'] },
      { key: 'd', label: 'Step Over', gw: 1.05, aliases: ['stepover'] },
    ],
    goal: ['⚽ *GOAL!* {player} sells the fake and scores! 🌀', '💥 *GOAL!* Keeper bought it! 🔥'],
    miss: ['🔄 {player} falls over after the fake — no shot!', '🧤 Keeper stays big and saves.'],
  },
  {
    build: ['🦶 {player} takes a touch around the defender...', 'Opening the angle...'],
    options: [
      { key: 'a', label: 'Touch & Shoot', gw: 1.2, aliases: ['shot', 'finish'] },
      { key: 'b', label: 'Touch & Pass', gw: 1.0, aliases: ['pass'] },
      { key: 'c', label: 'Touch & Chip', gw: 1.1, aliases: ['chip'] },
      { key: 'd', label: 'Spin', gw: 1.05, aliases: ['spin'] },
    ],
    goal: ['⚽ *GOAL!* {player} takes the touch and finishes! 🦶', '💥 *GOAL!* Great control! 🔥'],
    miss: ['🔄 {player} takes too heavy a touch — cleared!', '🧤 Keeper saves.'],
  },
  {
    build: ['🌀 {player} drags the ball inside with a sombrero...', 'Trying to lift it over...'],
    options: [
      { key: 'a', label: 'Sombrero Finish', gw: 1.1, aliases: ['finish', 'shot'] },
      { key: 'b', label: 'Sombrero Run', gw: 1.05, aliases: ['run'] },
      { key: 'c', label: 'Volley', gw: 1.1, aliases: ['volley'] },
      { key: 'd', label: 'Recover', gw: 0.9, aliases: ['recover'] },
    ],
    goal: ['⚽ *GOAL!* {player} sombreros and scores! 🌀', '🌟 *GOAL!* Fancy and effective! 🔥'],
    miss: ['😬 {player} loses the sombrero — cleared!', '🧱 Blocked.'],
  },
  {
    build: ['🥅 {player} is clean through after a defensive slip...', 'Keeper comes out...'],
    options: [
      { key: 'a', label: 'Chip', gw: 1.2, aliases: ['chip'] },
      { key: 'b', label: 'Round', gw: 1.15, aliases: ['round'] },
      { key: 'c', label: 'Toe Poke', gw: 1.1, aliases: ['poke'] },
      { key: 'd', label: 'Panenka', gw: 1.25, aliases: ['panenka'] },
    ],
    goal: ['⚽ *GOAL!* {player} punishes the slip! 🥅', '💥 *GOAL!* Clinical! 🔥'],
    miss: ['🧤 Keeper rushes out and blocks!', '😱 {player} slots it wide!'],
  },

  // ─── NEW SITUATIONS (build-ups + set pieces + defending) ──────────────────
  {
    type: 'defend',
    build: ['🚨 {team} break at speed...', '{opp} are exposed at the back!', '{player} is the last line of defence...'],
    options: [
      { key: 'a', label: 'Last-Ditch Tackle', gw: 1.2, aliases: ['tackle'] },
      { key: 'b', label: 'Stand Tall', gw: 1.05, aliases: ['block', 'stand'] },
      { key: 'c', label: 'Show Outside', gw: 1.1, aliases: ['show', 'channel'] },
      { key: 'd', label: 'Foul Smart', gw: 0.95, aliases: ['foul'] },
    ],
    win: ['🧱 *CLEAN TACKLE!* {player} nicks it away — danger cleared! 🛡️', '💪 *READ IT!* {player} wins the ball and relieves the pressure! 🔄'],
    lose: ['😰 {player} gets spun — {team} still have the ball! ⚠️', '🔥 {player} is beaten for pace — {team} pour forward!'],
  },
  {
    type: 'defend',
    build: ['🎯 {team} line up a shot...', '{player} steps up to block...'],
    options: [
      { key: 'a', label: 'Block', gw: 1.2, aliases: ['block'] },
      { key: 'b', label: 'Deflect', gw: 1.05, aliases: ['deflect'] },
      { key: 'c', label: 'Charge', gw: 1.1, aliases: ['charge', 'rush'] },
      { key: 'd', label: 'Dive In', gw: 0.9, aliases: ['dive'] },
    ],
    win: ['🧱 *BLOCKED!* {player} throws the body in the way! 💥', '✋ *DEFLECTED!* {player} takes one for the team! 🛡️'],
    lose: ['😬 {player} is wrong-footed — shot is coming in! ⚠️', '🔥 {player} can\'t get there — {team} are through on goal!'],
  },
  {
    type: 'defend',
    build: ['🧠 {opp} win it in midfield...', '{player} is the shield in front of the back line...'],
    options: [
      { key: 'a', label: 'Press Passer', gw: 1.15, aliases: ['press'] },
      { key: 'b', label: 'Cut Lane', gw: 1.1, aliases: ['cut', 'lane'] },
      { key: 'c', label: 'Track Runner', gw: 1.05, aliases: ['track'] },
      { key: 'd', label: 'Drop Deep', gw: 0.95, aliases: ['drop'] },
    ],
    win: ['🪤 *INTERCEPTED!* {player} reads the pass and steps in! 🔄', '🧠 *SMART!* {player} cuts out the danger! 🛡️'],
    lose: ['😤 {player} is dragged out of position — gap opens! ⚠️', '🔥 {team} slip the pass past {player}!'],
  },
  {
    type: 'defend',
    build: ['🧤 Keeper is the sweeper...', '{player} races off his line to close down...'],
    options: [
      { key: 'a', label: 'Smother', gw: 1.2, aliases: ['smother'] },
      { key: 'b', label: 'Narrow Angle', gw: 1.1, aliases: ['narrow'] },
      { key: 'c', label: 'Claim Cross', gw: 1.05, aliases: ['claim'] },
      { key: 'd', label: 'Rush Out', gw: 0.95, aliases: ['rush'] },
    ],
    win: ['🧤 *SMOTHERED!* {player} claims it with the striker on him! 🤲', '⚡ *OFF HIS LINE!* {player} snuffs out the chance! 🛡️'],
    lose: ['😱 {player} comes out and gets beaten — empty net! ⚠️', '🔥 {player} mistimes it — {team} roll it past!'],
  },
  {
    type: 'defend',
    build: ['🌀 {team} try to play through the middle...', '{player} sniffs the interception...'],
    options: [
      { key: 'a', label: 'Step In', gw: 1.2, aliases: ['step', 'intercept'] },
      { key: 'b', label: 'Bait', gw: 1.05, aliases: ['bait'] },
      { key: 'c', label: 'Double Up', gw: 1.1, aliases: ['double'] },
      { key: 'd', label: 'Hold Shape', gw: 0.95, aliases: ['hold', 'shape'] },
    ],
    win: ['🪤 *PICKED OFF!* {player} steps in and wins it! 🔄', '🧠 *POSITIONED!* {player} reads it perfectly! 🛡️'],
    lose: ['😬 {player} bites — {team} slip it through! ⚠️', '🔥 {player} is bypassed — {team} attack!'],
  },
  {
    type: 'defend',
    build: ['💥 Shot incoming!', '{player} throws the body on the line...'],
    options: [
      { key: 'a', label: 'Body Block', gw: 1.2, aliases: ['body', 'block'] },
      { key: 'b', label: 'Leg Block', gw: 1.1, aliases: ['leg'] },
      { key: 'c', label: 'Header Clear', gw: 1.05, aliases: ['header', 'clear'] },
      { key: 'd', label: 'Lunge', gw: 0.9, aliases: ['lunge'] },
    ],
    win: ['🧱 *WALL!* {player} blocks it with everything! 💥', '✋ *CLEARED!* {player} puts it behind for a corner! 🛡️'],
    lose: ['😩 {player} can\'t get there — it\'s through! ⚠️', '🔥 {player} is beaten — {team} are in!'],
  },
  {
    type: 'defend',
    build: ['⚡ {team} counter fast...', '{player} slides in to halt it...'],
    options: [
      { key: 'a', label: 'Slide Tackle', gw: 1.15, aliases: ['slide', 'tackle'] },
      { key: 'b', label: 'Touch Tight', gw: 1.05, aliases: ['tight'] },
      { key: 'c', label: 'Shoulder', gw: 1.1, aliases: ['shoulder'] },
      { key: 'd', label: 'Pull', gw: 0.95, aliases: ['pull'] },
    ],
    win: ['🔄 *SLIDE!* {player} wins the ball cleanly! 🛡️', '💪 *SHARPLY DEFENDED!* {player} kills the counter! 🔒'],
    lose: ['😤 {player} catches a handful of grass — free kick! ⚠️', '🔥 {player} is skipped past — {team} race on!'],
  },
  {
    type: 'defend',
    build: ['🤹 {team} star is dancing...', '{player} must contain him...'],
    options: [
      { key: 'a', label: 'Contain', gw: 1.15, aliases: ['contain'] },
      { key: 'b', label: 'Force Wide', gw: 1.1, aliases: ['wide', 'force'] },
      { key: 'c', label: 'Double Team', gw: 1.05, aliases: ['double'] },
      { key: 'd', label: 'Lunge', gw: 0.9, aliases: ['lunge'] },
    ],
    win: ['🔒 *CONTAINED!* {player} shepherds him into trouble! 🛡️', '🧠 *DISCIPLINED!* {player} forces the error! 🔄'],
    lose: ['😬 {player} is nutmegged — again! ⚠️', '🔥 {player} is roasted — {team} break through!'],
  },
  {
    build: ['🆓 Inswinging free kick...', '{player} stands over the ball, rain falling...', 'The wall jumps...'],
    options: [
      { key: 'a', label: 'Inswing', gw: 1.2, aliases: ['inswing', 'curl'] },
      { key: 'b', label: 'Low Drive', gw: 1.1, aliases: ['low', 'drive'] },
      { key: 'c', label: 'Near Post', gw: 1.05, aliases: ['near'] },
      { key: 'd', label: 'Switch', gw: 0.95, aliases: ['switch', 'pass'] },
    ],
    goal: ['⚽ *INSWINGER GOAL!* {player} finds the top corner! 😍', '💥 *GOAL!* Swerving beauty from {player}! 🔥'],
    miss: ['🧱 Wall blocks the inswinger!', '😩 {player} curls it just wide!'],
  },
  {
    build: ['🎯 Penalty awarded after a foul in the box!', '{player} places it down, eyes locked on goal...', 'The keeper guesses left...'],
    options: [
      { key: 'a', label: 'Top Corner', gw: 1.2, aliases: ['corner', 'top'] },
      { key: 'b', label: 'Panenka', gw: 1.25, aliases: ['panenka', 'chip'] },
      { key: 'c', label: 'Low Driven', gw: 1.15, aliases: ['low', 'drive'] },
      { key: 'd', label: 'Stutter', gw: 1.0, aliases: ['stutter'] },
    ],
    goal: ['⚽ *PENALTY GOAL!* {player} picks his spot! 😏', '💥 *GOAL FROM THE SPOT!* Ice cold, {player}! 🧊'],
    miss: ['🧤 Keeper goes the right way — SAVE! 🤯', '😩 {player} drags it wide — the waste!'],
  },
  {
    build: ['🆓 Long-range free kick, 30 yards...', '{player} backs away, measuring it...', 'The keeper sets the wall...'],
    options: [
      { key: 'a', label: 'Knuckle', gw: 1.2, aliases: ['knuckle'] },
      { key: 'b', label: 'Over Wall', gw: 1.1, aliases: ['over'] },
      { key: 'c', label: 'Whipped', gw: 1.05, aliases: ['whip', 'curl'] },
      { key: 'd', label: 'Roll Short', gw: 0.95, aliases: ['short', 'roll'] },
    ],
    goal: ['⚽ *FREE KICK GOAL!* {player} bends it round the wall! 😍', '💥 *GOAL!* Textbook set piece! 🔥'],
    miss: ['🧱 Wall heads it clear!', '😩 {player} catches it sweet but wide!'],
  },
  {
    build: ['🚩 Corner, near post...', '{player} peels off his marker...', 'The ball hangs up...'],
    options: [
      { key: 'a', label: 'Flick On', gw: 1.15, aliases: ['flick'] },
      { key: 'b', label: 'Glance', gw: 1.1, aliases: ['glance', 'header'] },
      { key: 'c', label: 'Power', gw: 1.2, aliases: ['power'] },
      { key: 'd', label: 'Back Post', gw: 0.95, aliases: ['back'] },
    ],
    goal: ['⚽ *NEAR-POST GOAL!* {player} flicks it in! 🤩', '💥 *GOAL!* Great corner routine! 🔥'],
    miss: ['🧤 Keeper punches it clear!', '😬 {player} can\'t connect cleanly!'],
  },
  {
    build: ['🤾 Quick throw-in...', '{player} takes it early and spins...', 'Space opens...'],
    options: [
      { key: 'a', label: 'Drive Forward', gw: 1.15, aliases: ['drive', 'run'] },
      { key: 'b', label: 'One-Two', gw: 1.05, aliases: ['onetwo', 'pass'] },
      { key: 'c', label: 'Switch', gw: 1.0, aliases: ['switch'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} turns the quick throw into a chance! ⚡', '🔥 *GOAL!* Caught {opp} cold! 💨'],
    miss: ['🔄 {opp} read it and clear.', '🧤 Keeper claims.'],
  },
  {
    build: ['⚡ Deep counter from {team}...', '{player} receives inside his own half...', 'One pass and they\'re off...'],
    options: [
      { key: 'a', label: 'Surge', gw: 1.2, aliases: ['surge', 'run'] },
      { key: 'b', label: 'Through', gw: 1.1, aliases: ['through', 'pass'] },
      { key: 'c', label: 'Switch', gw: 1.0, aliases: ['switch'] },
      { key: 'd', label: 'Hold', gw: 0.9, aliases: ['hold'] },
    ],
    goal: ['⚽ *GOAL!* {player} launches the counter and finishes! ⚡', '🔥 *GOAL!* Lightning break! 💨'],
    miss: ['🔄 The final ball is overhit.', '🧤 Keeper rushes out.'],
  },
  {
    build: ['🥅 One-on-one, {player} rounds the last man...', 'Keeper staying big...', 'Decision time...'],
    options: [
      { key: 'a', label: 'Chip', gw: 1.2, aliases: ['chip'] },
      { key: 'b', label: 'Round', gw: 1.15, aliases: ['round'] },
      { key: 'c', label: 'Toe Poke', gw: 1.1, aliases: ['poke'] },
      { key: 'd', label: 'Panenka', gw: 1.25, aliases: ['panenka'] },
    ],
    goal: ['⚽ *GOAL!* {player} dinks it past the keeper! 😍', '💥 *GOAL!* Composed finish! 🔥'],
    miss: ['🧤 Keeper smothers the chip!', '😱 {player} puts it wide!'],
  },
  {
    build: ['🔻 Low cross defended...', '{player} meets it at the near post...', 'Contact!'],
    options: [
      { key: 'a', label: 'Near Post', gw: 1.2, aliases: ['near', 'header'] },
      { key: 'b', label: 'Flick', gw: 1.0, aliases: ['flick'] },
      { key: 'c', label: 'Volley', gw: 1.15, aliases: ['volley'] },
      { key: 'd', label: 'Control', gw: 0.9, aliases: ['control'] },
    ],
    goal: ['⚽ *GOAL!* {player} steers it home off the cross! 🔻', '💥 *GOAL!* Poacher\'s finish! 🔥'],
    miss: ['🧱 Defender gets a toe to it!', '😬 {player} scuffs the chance.'],
  },
  {
    build: ['🪂 Cross falls perfectly...', '{player} arrives on the volley...', 'Sweet connection...'],
    options: [
      { key: 'a', label: 'Volley', gw: 1.2, aliases: ['volley'] },
      { key: 'b', label: 'Half-Volley', gw: 1.1, aliases: ['half'] },
      { key: 'c', label: 'Sidefoot', gw: 1.05, aliases: ['sidefoot'] },
      { key: 'd', label: 'Cushion', gw: 0.9, aliases: ['cushion'] },
    ],
    goal: ['⚽ *VOLLEY GOAL!* {player} catches it flush! 💥', '🌟 *GOAL!* What a strike! 🔥'],
    miss: ['😬 {player} skies the volley!', '🧤 Keeper holds.'],
  },
  {
    build: ['🌀 {team} work it down the right...', '{player} beats his man and cuts back...', 'Final third...'],
    options: [
      { key: 'a', label: 'Cut Inside', gw: 1.2, aliases: ['cut', 'shot'] },
      { key: 'b', label: 'Cross', gw: 1.0, aliases: ['cross'] },
      { key: 'c', label: 'Hug Line', gw: 0.95, aliases: ['hug'] },
      { key: 'd', label: 'Stepover', gw: 1.05, aliases: ['stepover'] },
    ],
    goal: ['⚽ *GOAL!* {player} cuts inside and buries it! 😍', '💥 *GOAL!* Winger\'s magic! 🔥'],
    miss: ['😬 {player} overcooks the cut-back.', '🧤 Keeper gathers.'],
  },
  {
    build: ['🟢 Through ball splits the defence...', '{player} is onto it like a greyhound...', 'One touch and shoot...'],
    options: [
      { key: 'a', label: 'First Touch', gw: 1.2, aliases: ['touch', 'finish'] },
      { key: 'b', label: 'Chip', gw: 1.15, aliases: ['chip'] },
      { key: 'c', label: 'Round', gw: 1.1, aliases: ['round'] },
      { key: 'd', label: 'Square', gw: 0.95, aliases: ['square', 'pass'] },
    ],
    goal: ['⚽ *GOAL!* {player} latches on and finishes! 🟢', '💥 *GOAL!* Perfect through ball! 🔥'],
    miss: ['🚩 {player} is a yard offside!', '🧤 Keeper out quickly.'],
  },
  {
    build: ['🎯 Penalty, high stakes...', '{player} strolls up, cheeky as ever...', 'Panenka on his mind...'],
    options: [
      { key: 'a', label: 'Panenka', gw: 1.25, aliases: ['panenka', 'chip'] },
      { key: 'b', label: 'Power', gw: 1.2, aliases: ['power', 'corner'] },
      { key: 'c', label: 'Down Middle', gw: 1.1, aliases: ['middle'] },
      { key: 'd', label: 'Wait', gw: 0.95, aliases: ['wait'] },
    ],
    goal: ['⚽ *PANENKA GOAL!* {player} rolls it down the middle! 😏', '💥 *GOAL!* Pure sauce! 🔥'],
    miss: ['😱 Keeper doesn\'t bite — SAVE! 🧤', '😩 {player} panics and skies it!'],
  },
];

function pickSituation() {
  return pick(SITUATIONS);
}

function fillPlaceholders(text, ctx) {
  return (text || '')
    .replace(/{player}/g, ctx.player || 'The attacker')
    .replace(/{team}/g, ctx.team || 'The team')
    .replace(/{opp}/g, ctx.opp || 'The opponent');
}

module.exports = { SITUATIONS, pickSituation, fillPlaceholders };
